"""Controlled Universal Capability Slot foundation.

This package is an additive extension surface under the existing Capability
Registry area. It creates candidate records only; it does not install,
activate, invoke, or mutate runtime capability state.
"""

from .universal_capability_slot_types_v1 import (
    CapabilityBindingCandidateV1,
    CapabilityBindingOutcomeV1,
    CapabilityInvocationCandidateV1,
    CapabilityModuleV1,
    CapabilityGapCandidateV1,
    ModuleAdmissionCandidateV1,
    ModuleAdmissionOutcomeV1,
    CapabilityRegulationCandidateV1,
    CapabilityRequirementV1,
    CapabilityScopeAssessmentV1,
    CapabilityResolutionCandidateV1,
    CapabilitySelfViewV1,
    CapabilityUsageRecordV1,
    CapabilityOutcomeAssessmentV1,
    IndividualCapabilityExperienceProfileV1,
    CapabilityWeaknessCandidateV1,
    HiveCapabilityFeedbackCandidateV1,
    HiveCapabilityDemandCandidateV1,
    OfficialCapabilityModuleV1,
    SlotCompatibilityAssessmentV1,
    SlotLifecycleCandidateV1,
    SlotModuleBindingV1,
    UniversalCapabilitySlotV1,
)
from .official_capability_catalog_types_v1 import (
    CapabilityAssetMappingV1,
    CapabilitySemanticAnnotationV1,
    OfficialCapabilityCatalogEntryV1,
    OfficialCapabilityCatalogV1,
    SlotCompatibilityMappingV1,
)
from .cognitive_need_capability_requirement_bridge_types_v1 import (
    CognitiveNeedCandidateV1,
    CapabilityRequirementFormationCandidateV1,
    CognitiveNeedReplanningCandidateV1,
    CognitiveNextStepAssessmentV1,
)
from .observation_demand_capability_resolution_v1 import (
    GovernedCapabilityInventoryEntryV1,
    GovernedObservationCapabilityRequirementMappingV1,
    ObservationDemandCapabilityRequirementAdapterV1,
    ObservationDemandCapabilityResolutionCandidateV1,
    ObservationDemandCapabilityResolutionInputV1,
    ObservationDemandCapabilityResolutionResultV1,
    resolve_observation_demand_capabilities,
)

__all__ = [
    "CapabilityBindingCandidateV1",
    "CapabilityBindingOutcomeV1",
    "CapabilityInvocationCandidateV1",
    "CapabilityModuleV1",
    "CapabilityGapCandidateV1",
    "ModuleAdmissionCandidateV1",
    "ModuleAdmissionOutcomeV1",
    "CapabilityRegulationCandidateV1",
    "CapabilityRequirementV1",
    "CapabilityScopeAssessmentV1",
    "CapabilityResolutionCandidateV1",
    "CapabilitySelfViewV1",
    "CapabilityUsageRecordV1",
    "CapabilityOutcomeAssessmentV1",
    "IndividualCapabilityExperienceProfileV1",
    "CapabilityWeaknessCandidateV1",
    "HiveCapabilityFeedbackCandidateV1",
    "HiveCapabilityDemandCandidateV1",
    "OfficialCapabilityModuleV1",
    "SlotCompatibilityAssessmentV1",
    "SlotLifecycleCandidateV1",
    "SlotModuleBindingV1",
    "UniversalCapabilitySlotV1",
    "CapabilityAssetMappingV1",
    "CapabilitySemanticAnnotationV1",
    "OfficialCapabilityCatalogEntryV1",
    "OfficialCapabilityCatalogV1",
    "SlotCompatibilityMappingV1",
    "CognitiveNeedCandidateV1",
    "CapabilityRequirementFormationCandidateV1",
    "CognitiveNeedReplanningCandidateV1",
    "CognitiveNextStepAssessmentV1",
    "GovernedCapabilityInventoryEntryV1",
    "GovernedObservationCapabilityRequirementMappingV1",
    "ObservationDemandCapabilityRequirementAdapterV1",
    "ObservationDemandCapabilityResolutionCandidateV1",
    "ObservationDemandCapabilityResolutionInputV1",
    "ObservationDemandCapabilityResolutionResultV1",
    "resolve_observation_demand_capabilities",
]
