"""Static candidate-only capability boundary registry."""

from __future__ import annotations

from typing import Dict, Tuple


PHASE = "Phase-Luna-Candidate-Only-Authority-Grant-And-Mechanical-Command-Adapter-v1-001"

ROLE_A = "A_REASONING_ROLE"
ROLE_B = "B_CONTINGENCY_ROLE"
ROLE_LOOP = "LOOP_ENGINE"
ROLE_BRAIN = "BRAIN_GOVERNANCE"

A_AUTHORITIES: Tuple[str, ...] = (
    "REALITY_REASONING",
    "SELECT_CURRENT_NEED",
    "GENERATE_HYPOTHESIS",
    "JUDGE_EVIDENCE_RELEVANCE",
    "JUDGE_LOCAL_SUFFICIENCY",
    "JUDGE_RECONSIDERATION",
    "REQUEST_OBSERVATION",
    "REQUEST_CAPABILITY",
    "REQUEST_B",
    "DECIDE_LOCAL_CONTINUATION",
    "REQUEST_PAUSE",
    "REQUEST_WAIT",
    "REQUEST_RESUME",
    "REQUEST_CLOSURE",
)

B_AUTHORITIES: Tuple[str, ...] = (
    "CONTINGENCY_REASONING",
    "EXPLORE_ASSUMPTIONS",
    "ANALYZE_UNCERTAINTY_BOUNDARY",
    "FORM_CONDITIONAL_RESPONSE_CANDIDATE",
    "FORM_CONTINGENCY_RESULT",
)

LOOP_AUTHORITIES: Tuple[str, ...] = (
    "PERSIST_STATE",
    "RECORD_STATE_VERSION",
    "RECORD_REFS",
    "PAUSE_MECHANICALLY",
    "WAIT_MECHANICALLY",
    "RESUME_RECORDED_STATE",
    "FREEZE_FINAL_STATE",
    "ARCHIVE_HISTORY",
    "APPEND_TRACE",
)

LOOP_FORBIDDEN_AUTHORITIES: Tuple[str, ...] = (
    "JUDGE_SUFFICIENCY",
    "SELECT_NEED",
    "GENERATE_HYPOTHESIS",
    "SELECT_CAPABILITY",
    "REQUEST_B",
    "SPLIT_CONCERN",
    "MERGE_CONCERN",
    "ADOPT_RESULT",
    "DECLARE_TRUTH",
)

BRAIN_AUTHORITIES: Tuple[str, ...] = (
    "ADMIT_CONCERN",
    "ADMIT_CONCERN_SPLIT",
    "ADMIT_CONCERN_MERGE",
    "GOVERN_GLOBAL_GOAL",
    "GOVERN_GLOBAL_PRIORITY",
    "ASSIMILATE_RESULT",
)

KNOWN_AUTHORITIES: Tuple[str, ...] = tuple(
    dict.fromkeys(
        A_AUTHORITIES
        + B_AUTHORITIES
        + LOOP_AUTHORITIES
        + LOOP_FORBIDDEN_AUTHORITIES
        + BRAIN_AUTHORITIES
    )
)

ROLE_CAPABILITY_BOUNDARIES: Dict[str, Tuple[str, ...]] = {
    ROLE_A: A_AUTHORITIES,
    ROLE_B: B_AUTHORITIES,
    ROLE_LOOP: LOOP_AUTHORITIES,
    ROLE_BRAIN: BRAIN_AUTHORITIES,
}

LOOP_COMMAND_CAPABILITY: Dict[str, str] = {
    "MATERIALIZE": "PERSIST_STATE",
    "RECORD_STATE_VERSION": "RECORD_STATE_VERSION",
    "RECORD_NEED_REF": "RECORD_REFS",
    "RECORD_REQUIREMENT_REF": "RECORD_REFS",
    "RECORD_PENDING_CANDIDATE": "RECORD_REFS",
    "PAUSE": "PAUSE_MECHANICALLY",
    "WAIT": "WAIT_MECHANICALLY",
    "RESUME_KEEP": "RESUME_RECORDED_STATE",
    "RESUME_REPLAN": "RESUME_RECORDED_STATE",
    "SUPERSEDE_REQUIREMENT": "RECORD_REFS",
    "RECORD_B_BRANCH_REF": "RECORD_REFS",
    "CLOSE": "FREEZE_FINAL_STATE",
    "FREEZE_FINAL_STATE": "FREEZE_FINAL_STATE",
    "RECORD_OUTCOME_REF": "RECORD_REFS",
    "ARCHIVE_HISTORY_BOUNDARY": "ARCHIVE_HISTORY",
}

MECHANICAL_COMMANDS: Tuple[str, ...] = tuple(LOOP_COMMAND_CAPABILITY)

FAILURE_CLASSES: Tuple[str, ...] = (
    "CAPABILITY_BOUNDARY_VIOLATION",
    "AUTHORITY_NOT_GRANTED",
    "SCOPE_MISMATCH",
    "STALE_STATE_VERSION",
    "GRANT_REVOKED",
    "GRANT_EXPIRED",
    "RESPONSIBILITY_BINDING_INVALID",
    "MECHANICAL_COMMAND_ACCEPTED",
)

GRANT_STATUSES: Tuple[str, ...] = (
    "ACTIVE",
    "REJECTED",
    "REVOKED",
    "EXPIRED",
    "STALE",
)


def capability_boundary(role: str) -> Tuple[str, ...]:
    return ROLE_CAPABILITY_BOUNDARIES.get(role, ())


def command_capability(command_kind: str) -> str | None:
    return LOOP_COMMAND_CAPABILITY.get(command_kind)
