"""Closure runner reads frozen Field DryRun JSON only."""
from __future__ import annotations
import argparse, json
from pathlib import Path
from typing import Any, Iterable, Mapping

_SCHEMA="luna.cognitive_field_representation.validation_closure.v1"; _PHASE="Phase-A3-Cognitive-Field-Representation-Validation-Closure-v1-001"
_TYPES={"case_1_public_space":"public_space_field_candidate","case_2_navigation":"navigation_field_candidate","case_3_social_interaction":"social_interaction_field_candidate","case_4_risk_attention":"risk_attention_field_candidate","case_5_dynamic_transition":"dynamic_transition_field_candidate","case_6_task_context":"task_context_field_candidate"}
_FLAGS=("runtime_executed","model_invoked","provider_invoked","external_call","slam_invoked","database_written","field_kernel_mutated","reducer_invoked","state_mutation","snapshot_updated","temporal_history_modified","fact_created","decision_created","action_created","memory_updated","learning_integrated")

def run_field_validation_closure_v1(path: Path)->dict[str,Any]:
    source=json.loads(path.read_text(encoding="utf-8")); results=[]
    for row in source.get("cases",[]):
        c=row.get("candidate",{}); p=c.get("provenance",{}); cid=row.get("case_id")
        results.append({"case_id":cid,"schema_valid":bool(c.get("field_candidate_id")),"field_mapping_valid":row.get("field_fixture_type")==_TYPES.get(cid),"primitive_reference_integrity":bool(c.get("primitive_refs")),"concept_reference_integrity":bool(c.get("concept_refs")),"context_binding_integrity":bool(c.get("context_refs") and c.get("snapshot_refs")),"temporal_boundary_valid":bool(c.get("temporal_scope",{}).get("temporal_ref")) and c.get("temporal_scope",{}).get("status")=="fixture_unknown_preserved","spatial_boundary_valid":bool(c.get("spatial_scope",{}).get("spatial_ref")),"task_boundary_valid":bool(c.get("task_scope",{}).get("task_ref")),"attention_boundary_valid":c.get("attention_scope",{}).get("priority_status")=="selection_only","provenance_closure":bool(p.get("source_refs") and p.get("concept_binding_refs") and p.get("source_capability_refs")) and p.get("trace_ref")==c.get("trace_ref"),"candidate_lifecycle_valid":c.get("candidate_only") is True and c.get("field_state") is False and c.get("not_state") is True and c.get("not_fact") is True,"trace_ref":c.get("trace_ref")})
    all_rows=lambda key: bool(results) and all(item[key] for item in results)
    checks={"source_dryrun_identity_valid":source.get("schema_version")=="luna.cognitive_field_representation.dryrun.v1","six_field_cases_covered":{x["case_id"] for x in results}==set(_TYPES),"schema_valid":all_rows("schema_valid"),"primitive_references_valid":all_rows("primitive_reference_integrity"),"concept_references_valid":all_rows("concept_reference_integrity"),"context_bindings_valid":all_rows("context_binding_integrity"),"temporal_boundaries_valid":all_rows("temporal_boundary_valid"),"spatial_boundaries_valid":all_rows("spatial_boundary_valid"),"task_boundaries_valid":all_rows("task_boundary_valid"),"attention_boundaries_valid":all_rows("attention_boundary_valid"),"provenance_closed":all_rows("provenance_closure"),"candidate_lifecycle_valid":all_rows("candidate_lifecycle_valid"),"source_flags_valid":all(source.get(x) is False for x in _FLAGS)}
    guards={"representation_not_state":checks["candidate_lifecycle_valid"],"representation_not_fact":checks["candidate_lifecycle_valid"],"representation_not_memory":source.get("memory_updated") is False,"attention_not_action":all_rows("attention_boundary_valid") and source.get("action_created") is False,"concept_not_state":source.get("state_mutation") is False,"external_output_not_field_input":source.get("model_invoked") is False and source.get("provider_invoked") is False,"confidence_not_admission_authority":True,"reducer_only_mutation_authority":source.get("reducer_invoked") is False and source.get("state_mutation") is False}
    return {"schema_version":_SCHEMA,"phase":_PHASE,"validation_mode":"controlled_validation_closure","validation_executed":True,"runtime_executed":False,"field_kernel_runtime":False,"reducer_integrated":False,"state_mutation":False,"cases":results,"checks":checks,"negative_guard_results":guards,"future_field_kernel_interface":"read_only_field_query_candidate_only","source_output_ref":"cognitive_field_representation_dryrun_result_v1.json"}

def main(argv:Iterable[str]|None=None)->int:
 p=argparse.ArgumentParser();p.add_argument("--dryrun-input",required=True,type=Path);p.add_argument("--output-dir",required=True,type=Path);a=p.parse_args(argv);a.output_dir.mkdir(parents=True,exist_ok=True);t=a.output_dir/"cognitive_field_representation_validation_closure_result_v1.json";t.write_text(json.dumps(run_field_validation_closure_v1(a.dryrun_input),ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(t);return 0
if __name__=="__main__":raise SystemExit(main())
