# -*- coding: utf-8 -*-
"""Luna Gate Chain / Enforcement Gate System v1 — shared gate taxonomy."""

from __future__ import annotations

from typing import Any, Dict, Tuple

SYSTEM_ID = "luna_gate_chain_enforcement_gate_system_v1"
SYSTEM_NAME = "Luna Gate Chain / Enforcement Gate System"
SYSTEM_NAME_ZH = "Luna 门控链 / 执法门控体系"

GATE_TYPES: Tuple[str, ...] = (
    "enforcement_gate",
    "admission_gate",
    "oversight_check",
)

GATE_ENTRY_FIELDS: Tuple[str, ...] = (
    "gate_id",
    "gate_type",
    "architectural_layer",
    "applies_to_current_phase",
    "current_status",
    "consumed_object_type",
    "emitted_object_type",
    "invoked_now",
    "required_later",
    "blocked_path_ref",
    "owner_module",
    "non_claim",
)

GATE_CHAIN_COVERAGE_CONFIRMATIONS: Tuple[str, ...] = (
    "gate coverage exists even if gate is not invoked now",
    "no gate invocation occurs in Output Candidate DryRun",
    "user_output_candidate does not bypass gate chain",
    "memory/worldmodel/task/navigation/action gates remain blocked",
    "Health Oversight remains external to Constitution-Bus",
    "gate_result_candidate not generated now",
    "enforcement_result_candidate not generated now",
)

GATE_CHAIN_REQUIREMENTS: Tuple[str, ...] = (
    "user_output_constitution_gate_later",
    "safety_gate_later",
    "speech_gate_if_voice_later",
    "display_gate_if_display_later",
    "privacy_gate_if_sensitive_later",
    "memory_admission_gate_blocked_now",
    "worldmodel_admission_gate_blocked_now",
    "navigation_action_gate_blocked_now",
    "task_state_commit_gate_blocked_now",
    "controlled_runtime_gate_required_later",
)

GATE_INVOCATION_BLOCKED_PATHS: Tuple[str, ...] = (
    "dryrun_to_memory_admission",
    "dryrun_to_worldmodel_admission",
    "dryrun_to_task_state_commit_gate",
    "dryrun_to_navigation_action_gate",
    "dryrun_to_privacy_gate_invocation",
    "dryrun_to_identity_gate_invocation",
    "dryrun_to_notification_gate_invocation",
    "dryrun_to_authorization_gate_invocation",
    "dryrun_to_provider_readiness_gate_invocation",
)

FIRST_PERSON_OUTPUT_GATE_CHAIN_ENTRIES: Tuple[Dict[str, Any], ...] = (
    {
        "gate_id": "user_output_constitution_gate",
        "gate_name": "User Output Constitution Gate",
        "gate_category": "output_communication_gates",
        "gate_type": "enforcement_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": True,
        "current_status": "required_later",
        "consumed_object_type": "user_output_candidate",
        "emitted_object_type": "constraint_bundle_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_safety_gate_invocation",
        "owner_module": "midplatform_user_output_constitution_v1",
        "non_claim": "constitution gate coverage ≠ constitution invoked now",
    },
    {
        "gate_id": "safety_gate",
        "gate_name": "Safety Gate",
        "gate_category": "output_communication_gates",
        "gate_type": "enforcement_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": True,
        "current_status": "required_later",
        "consumed_object_type": "user_output_candidate+constraint_bundle",
        "emitted_object_type": "enforcement_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_safety_gate_invocation",
        "owner_module": "midplatform_safety_gate_v1",
        "non_claim": "safety gate coverage ≠ safety enforcement now",
    },
    {
        "gate_id": "speech_gate",
        "gate_name": "Speech Gate",
        "gate_category": "output_communication_gates",
        "gate_type": "enforcement_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": True,
        "current_status": "required_if_voice_later",
        "consumed_object_type": "enforcement_result_candidate+user_output_candidate",
        "emitted_object_type": "gate_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_speech_gate_invocation",
        "owner_module": "midplatform_speech_gate_v1",
        "non_claim": "speech gate coverage ≠ speech output now",
    },
    {
        "gate_id": "display_gate",
        "gate_name": "Display Gate",
        "gate_category": "output_communication_gates",
        "gate_type": "enforcement_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": True,
        "current_status": "required_if_display_later",
        "consumed_object_type": "enforcement_result_candidate+user_output_candidate",
        "emitted_object_type": "gate_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_display_gate_invocation",
        "owner_module": "midplatform_display_gate_v1",
        "non_claim": "display gate coverage ≠ display output now",
    },
    {
        "gate_id": "notification_gate",
        "gate_name": "Notification Gate",
        "gate_category": "output_communication_gates",
        "gate_type": "enforcement_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "deferred_later",
        "consumed_object_type": "user_output_candidate",
        "emitted_object_type": "gate_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_notification_gate_invocation",
        "owner_module": "midplatform_notification_gate_v1_later",
        "non_claim": "notification gate deferred ≠ notification sent now",
    },
    {
        "gate_id": "authorization_gate",
        "gate_name": "Authorization Gate",
        "gate_category": "runtime_provider_gates",
        "gate_type": "admission_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "not_applicable_now_required_for_runtime_later",
        "consumed_object_type": "runtime_authorization_request_candidate",
        "emitted_object_type": "authorization_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_authorization_gate_invocation",
        "owner_module": "midplatform_authorization_gate_v1",
        "non_claim": "authorization gate coverage ≠ runtime authorized now",
    },
    {
        "gate_id": "provider_readiness_gate",
        "gate_name": "Provider Readiness Gate",
        "gate_category": "runtime_provider_gates",
        "gate_type": "admission_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "not_applicable_now_required_for_provider_later",
        "consumed_object_type": "provider_readiness_request_candidate",
        "emitted_object_type": "provider_readiness_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_provider_readiness_gate_invocation",
        "owner_module": "midplatform_provider_readiness_gate_v1",
        "non_claim": "provider readiness coverage ≠ provider invoked now",
    },
    {
        "gate_id": "controlled_runtime_gate",
        "gate_name": "Controlled Runtime Gate",
        "gate_category": "runtime_provider_gates",
        "gate_type": "admission_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "required_for_runtime_later",
        "consumed_object_type": "controlled_runtime_admission_request_candidate",
        "emitted_object_type": "runtime_admission_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_controlled_runtime_enable",
        "owner_module": "midplatform_controlled_runtime_v1",
        "non_claim": "controlled runtime gate coverage ≠ runtime enabled now",
    },
    {
        "gate_id": "memory_admission_gate",
        "gate_name": "Memory Admission Gate",
        "gate_category": "state_knowledge_admission_gates",
        "gate_type": "admission_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "blocked_now_required_for_memory_write_later",
        "consumed_object_type": "memory_write_request_candidate",
        "emitted_object_type": "memory_admission_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_memory_admission",
        "owner_module": "midplatform_memory_admission_gate_v1_later",
        "non_claim": "memory admission blocked now ≠ memory write allowed",
    },
    {
        "gate_id": "worldmodel_admission_gate",
        "gate_name": "WorldModel Admission Gate",
        "gate_category": "state_knowledge_admission_gates",
        "gate_type": "admission_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "blocked_now_required_for_worldmodel_write_later",
        "consumed_object_type": "worldmodel_write_request_candidate",
        "emitted_object_type": "worldmodel_admission_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_worldmodel_admission",
        "owner_module": "midplatform_worldmodel_admission_gate_v1_later",
        "non_claim": "worldmodel admission blocked now ≠ worldmodel write allowed",
    },
    {
        "gate_id": "task_state_commit_gate",
        "gate_name": "Task State Commit Gate",
        "gate_category": "state_knowledge_admission_gates",
        "gate_type": "admission_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "blocked_now_required_for_task_commit_later",
        "consumed_object_type": "task_state_commit_request_candidate",
        "emitted_object_type": "task_state_commit_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_task_state_commit_gate",
        "owner_module": "midplatform_task_state_commit_gate_v1_later",
        "non_claim": "task state commit blocked now ≠ task state committed",
    },
    {
        "gate_id": "navigation_action_gate",
        "gate_name": "Navigation Action Gate",
        "gate_category": "navigation_action_gates",
        "gate_type": "admission_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "blocked_now_required_for_navigation_action_later",
        "consumed_object_type": "navigation_action_request_candidate",
        "emitted_object_type": "navigation_action_admission_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_navigation_action_gate",
        "owner_module": "midplatform_navigation_action_gate_v1_later",
        "non_claim": "navigation action gate blocked now ≠ navigation action executed",
    },
    {
        "gate_id": "device_action_gate",
        "gate_name": "Device Action Gate",
        "gate_category": "navigation_action_gates",
        "gate_type": "admission_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "deferred_later",
        "consumed_object_type": "device_action_request_candidate",
        "emitted_object_type": "device_action_admission_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_real_navigation_action",
        "owner_module": "midplatform_device_action_gate_v1_later",
        "non_claim": "device action gate deferred ≠ device action now",
    },
    {
        "gate_id": "privacy_gate",
        "gate_name": "Privacy Gate",
        "gate_category": "identity_privacy_gates",
        "gate_type": "enforcement_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "required_later_for_sensitive_output_person_recognition_reading",
        "consumed_object_type": "user_output_candidate+identity_context_candidate",
        "emitted_object_type": "privacy_enforcement_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_privacy_gate_invocation",
        "owner_module": "midplatform_privacy_gate_v1_later",
        "non_claim": "privacy gate required later ≠ privacy enforced now",
    },
    {
        "gate_id": "identity_personal_continuity_gate",
        "gate_name": "Identity / Personal Continuity Gate",
        "gate_category": "identity_privacy_gates",
        "gate_type": "enforcement_gate",
        "architectural_layer": "enforcement_layer",
        "applies_to_current_phase": False,
        "current_status": "required_later_for_personal_continuity_person_recognition",
        "consumed_object_type": "identity_context_candidate+personal_continuity_context_candidate",
        "emitted_object_type": "identity_continuity_enforcement_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_identity_gate_invocation",
        "owner_module": "midplatform_identity_personal_continuity_gate_v1_later",
        "non_claim": "identity gate required later ≠ person identity asserted now",
    },
    {
        "gate_id": "health_oversight_check",
        "gate_name": "Health Enforcement Supervisor / Health Oversight Check",
        "gate_category": "health_oversight",
        "gate_type": "oversight_check",
        "architectural_layer": "external_oversight_layer",
        "applies_to_current_phase": True,
        "current_status": "external_supervision_ref_required_not_bus_self_judgement",
        "consumed_object_type": "health_signal_bundle",
        "emitted_object_type": "health_supervision_result_candidate",
        "invoked_now": False,
        "required_later": True,
        "blocked_path_ref": "dryrun_to_health_enforcement_supervisor_runtime_enable",
        "owner_module": "health_enforcement_supervisor_v1",
        "non_claim": "health oversight external ≠ Constitution-Bus self-judgement",
    },
)

GATE_CATEGORIES: Tuple[str, ...] = (
    "output_communication_gates",
    "runtime_provider_gates",
    "state_knowledge_admission_gates",
    "navigation_action_gates",
    "identity_privacy_gates",
    "health_oversight",
)
