# -*- coding: utf-8 -*-
"""Field-First Model Document Capability Review item definitions v1."""

from __future__ import annotations

from typing import Any, Dict, Tuple

REVIEW_PRINCIPLES: Dict[str, Any] = {
    "principles_id": "model_document_review_principles_v1",
    "rules": (
        "review_by_luna_requirements_not_model_marketing",
        "document_review_not_model_selection",
        "no_real_integration",
        "model_output_still_candidate",
        "external_model_cannot_define_luna_core",
    ),
}

REVIEW_ITEM_FIELDS: Tuple[str, ...] = (
    "model_project_id", "display_name", "model_room", "operation_node_refs",
    "requirement_matrix_refs", "official_docs_refs", "repo_refs", "paper_refs",
    "open_source_status", "license_status", "weights_available", "model_weights_required",
    "runtime_requirements", "hardware_requirements", "input_supported", "output_supported",
    "structured_output_supported", "confidence_output_supported", "timestamp_or_streaming_supported",
    "tracking_or_temporal_supported", "spatial_output_supported", "graph_output_supported",
    "candidate_output_mapping", "adapter_feasibility", "edge_deployment_feasibility",
    "known_failure_modes_documented", "missing_required_capabilities", "satisfies_phase1_minimum",
    "integration_risk", "runtime_risk", "hardware_risk", "governance_risk",
    "recommended_status", "reason_for_status", "next_action",
)

RECOMMENDED_STATUS_OPTIONS: Tuple[str, ...] = (
    "reference_only", "candidate_for_future_adapter", "candidate_for_near_term_adapter",
    "unsuitable_for_phase_1", "deferred_due_to_runtime_cost", "deferred_due_to_missing_outputs",
)


def _review(
    model_project_id: str, display_name: str, model_room: str,
    operation_node_refs: Tuple[str, ...], recommended_status: str, reason: str, next_action: str,
    **kwargs: Any,
) -> Dict[str, Any]:
    base: Dict[str, Any] = {
        "model_project_id": model_project_id, "display_name": display_name, "model_room": model_room,
        "operation_node_refs": list(operation_node_refs),
        "requirement_matrix_refs": list(operation_node_refs),
        "official_docs_refs": kwargs.get("docs", [f"https://github.com/placeholder/{model_project_id}"]),
        "repo_refs": kwargs.get("repo", [f"https://github.com/placeholder/{model_project_id}"]),
        "paper_refs": kwargs.get("papers", []),
        "open_source_status": kwargs.get("oss", "open_source"),
        "license_status": kwargs.get("license", "pending_verification"),
        "weights_available": kwargs.get("weights", True),
        "model_weights_required": kwargs.get("weights_req", True),
        "runtime_requirements": kwargs.get("runtime", "document_review_only"),
        "hardware_requirements": kwargs.get("hardware", "medium"),
        "input_supported": kwargs.get("inputs", []),
        "output_supported": kwargs.get("outputs", []),
        "structured_output_supported": kwargs.get("structured", False),
        "confidence_output_supported": kwargs.get("confidence", False),
        "timestamp_or_streaming_supported": kwargs.get("streaming", False),
        "tracking_or_temporal_supported": kwargs.get("tracking", False),
        "spatial_output_supported": kwargs.get("spatial", False),
        "graph_output_supported": kwargs.get("graph", False),
        "candidate_output_mapping": kwargs.get("candidates") if kwargs.get("candidates") is not None else [],
        "adapter_feasibility": kwargs.get("adapter", "feasible_with_adapter"),
        "edge_deployment_feasibility": kwargs.get("edge", "medium"),
        "known_failure_modes_documented": kwargs.get("failures", []),
        "missing_required_capabilities": kwargs.get("missing", []),
        "satisfies_phase1_minimum": kwargs.get("phase1", False),
        "integration_risk": kwargs.get("int_risk", "medium"),
        "runtime_risk": kwargs.get("rt_risk", "medium"),
        "hardware_risk": kwargs.get("hw_risk", "medium"),
        "governance_risk": kwargs.get("gov_risk", "low"),
        "recommended_status": recommended_status,
        "reason_for_status": reason,
        "next_action": next_action,
    }
    return base


MODEL_REVIEW_ITEMS: Tuple[Dict[str, Any], ...] = (
    _review("SAM2", "SAM 2", "visual_perception_room", ("visual_object_segmentation_tracking",),
            "candidate_for_future_adapter", "docs_confirm_segmentation_and_video_mask_tracking_but_gpu_heavy",
            "keep_adapter_placeholder_defer_download",
            docs=["https://github.com/facebookresearch/sam2"], outputs=["mask", "video_segmentation"],
            candidates=["MaskObservationCandidate", "TrackObservationCandidate"], tracking=True, confidence=True,
            failures=["occlusion", "low_light", "motion_blur"], missing=["open_vocabulary_labels_native"],
            phase1=False, hw_risk="high", rt_risk="high"),
    _review("Grounded_SAM2", "Grounded SAM 2", "visual_perception_room", ("visual_object_segmentation_tracking",),
            "candidate_for_near_term_adapter", "docs_confirm_open_vocab_grounding_tracking_segmentation",
            "priority_adapter_design_after_owner_review",
            outputs=["bbox", "mask", "track"], candidates=["ObjectObservationCandidate", "MaskObservationCandidate", "TrackObservationCandidate"],
            tracking=True, confidence=True, structured=True, phase1=True, int_risk="medium", hw_risk="high"),
    _review("ByteTrack", "ByteTrack", "visual_perception_room", ("visual_object_segmentation_tracking",),
            "candidate_for_near_term_adapter", "docs_confirm_multi_object_tracking_track_id",
            "adapter_design_for_track_observation_candidate",
            outputs=["bbox", "track_id"], candidates=["TrackObservationCandidate"], tracking=True, confidence=True, phase1=True),
    _review("YOLO_lightweight", "YOLO Lightweight", "visual_perception_room", ("visual_object_segmentation_tracking",),
            "candidate_for_near_term_adapter", "docs_support_lightweight_object_detection_edge_candidate",
            "evaluate_specific_yolo_variant_in_download_planning",
            outputs=["bbox", "class", "confidence"], candidates=["ObjectObservationCandidate"], confidence=True, edge="high", phase1=True),
    _review("GroundingDINO", "Grounding DINO", "visual_perception_room", ("visual_object_segmentation_tracking",),
            "candidate_for_future_adapter", "open_vocab_detection_useful_but_heavy_pipeline",
            "reference_for_grounded_sam2_pipeline", outputs=["bbox", "text_prompt_detection"], confidence=True, hw_risk="high"),
    _review("Florence2", "Florence-2", "visual_perception_room", ("visual_object_segmentation_tracking",),
            "deferred_due_to_runtime_cost", "vlm_captioning_useful_but_not_primary_phase1_visual_adapter",
            "keep_reference_only_for_future", outputs=["caption", "detection"], structured=True, rt_risk="high"),
    _review("DINO_X", "DINO-X", "visual_perception_room", ("visual_object_segmentation_tracking",),
            "deferred_due_to_missing_outputs", "placeholder_pipeline_docs_insufficient_for_phase1_commitment",
            "document_gap_followup", missing=["confirmed_track_id", "confirmed_edge_api"]),
    _review("PaddleOCR", "PaddleOCR", "ocr_text_perception_room", ("ocr_text_perception",),
            "candidate_for_near_term_adapter", "docs_confirm_det_rec_regions_confidence_chinese_english",
            "priority_ocr_adapter_design",
            docs=["https://github.com/PaddlePaddle/PaddleOCR"], outputs=["text_box", "text", "confidence"],
            candidates=["TextObservationCandidate", "TextRegionCandidate"], confidence=True, structured=True, edge="medium", phase1=True),
    _review("RapidOCR", "RapidOCR", "ocr_text_perception_room", ("ocr_text_perception",),
            "candidate_for_near_term_adapter", "docs_confirm_lightweight_ocr_det_rec",
            "alternate_ocr_adapter_candidate", outputs=["text_box", "text"], confidence=True, edge="high", phase1=True),
    _review("Whisper", "Whisper", "audio_speech_perception_room", ("audio_speech_speaker",),
            "candidate_for_near_term_adapter", "docs_confirm_asr_segments_timestamps_multilingual",
            "speech_adapter_design", outputs=["transcript", "segments"], streaming=True, confidence=True, phase1=True),
    _review("faster_whisper", "faster-whisper", "audio_speech_perception_room", ("audio_speech_speaker",),
            "candidate_for_near_term_adapter", "docs_confirm_efficient_asr_edge_candidate",
            "edge_asr_adapter_candidate", outputs=["transcript", "segments"], streaming=True, edge="high", phase1=True),
    _review("SenseVoice", "SenseVoice", "audio_speech_perception_room", ("audio_speech_speaker",),
            "candidate_for_future_adapter", "docs_suggest_chinese_asr_and_emotion_but_adapter_mapping_needed",
            "verify_intent_hint_mapping", outputs=["transcript", "emotion"], missing=["confirmed_intent_hint_schema"]),
    _review("pyannote_audio", "pyannote.audio", "audio_speech_perception_room", ("audio_speech_speaker",),
            "candidate_for_future_adapter", "docs_confirm_speaker_diarization_segments",
            "speaker_observation_adapter_design", outputs=["speaker_segments"], streaming=True, missing=["speaker_identity_fact_write_forbidden_by_design"]),
    _review("VAD_placeholder", "VAD Placeholder", "audio_speech_perception_room", ("audio_speech_speaker",),
            "deferred_due_to_missing_outputs", "no_specific_project_selected_yet",
            "select_vad_library_in_download_planning", missing=["project_selection", "documented_api"]),
    _review("voiceprint_placeholder", "Voiceprint Placeholder", "audio_speech_perception_room", ("audio_speech_speaker",),
            "deferred_due_to_missing_outputs", "no_specific_voiceprint_project_selected",
            "defer_until_governance_review", missing=["project_selection", "privacy_governance_plan"]),
    _review("Kimera", "Kimera", "spatial_slam_scene_graph_room", ("spatial_slam_dynamic_scene_graph",),
            "reference_only", "docs_confirm_vio_metric_semantic_slam_but_heavy_rgbd_imu_runtime",
            "structure_reference_for_field_model_not_runtime",
            papers=["Kimera RSS 2019"], graph=True, spatial=True, hw_risk="high", rt_risk="high", phase1=False),
    _review("Hydra", "Hydra", "spatial_slam_scene_graph_room", ("spatial_slam_dynamic_scene_graph",),
            "reference_only", "docs_confirm_realtime_3d_scene_graph_construction",
            "field_model_three_layer_structure_reference",
            graph=True, spatial=True, hw_risk="high", rt_risk="high", phase1=False),
    _review("HOV_SG", "HOV-SG", "spatial_slam_scene_graph_room", ("spatial_slam_dynamic_scene_graph",),
            "reference_only", "open_vocab_hierarchical_3d_scene_graph_long_term_reference",
            "not_first_version_dependency", graph=True, missing=["realtime_wearable_confirmation"]),
    _review("Open3DSG", "Open3DSG", "spatial_slam_scene_graph_room", ("spatial_slam_dynamic_scene_graph",),
            "reference_only", "point_cloud_scene_graph_query_long_term_reference",
            "not_phase1_runtime", graph=True, spatial=True, hw_risk="high"),
    _review("RTG_SLAM_placeholder", "RTG-SLAM Placeholder", "spatial_slam_scene_graph_room", ("spatial_slam_dynamic_scene_graph",),
            "deferred_due_to_missing_outputs", "placeholder_no_document_review_target_yet", "add_when_project_selected"),
    _review("Splatt3R_SLAM_placeholder", "Splatt3R-SLAM Placeholder", "spatial_slam_scene_graph_room", ("spatial_slam_dynamic_scene_graph",),
            "deferred_due_to_missing_outputs", "placeholder_no_document_review_target_yet", "add_when_project_selected"),
    _review("Esper", "Esper", "ecs_entity_component_room", ("ecs_entity_component",),
            "reference_only", "docs_confirm_python_lightweight_ecs_reference",
            "dataclass_skeleton_primary_esper_reference_only", edge="high", phase1=False, weights_req=False),
    _review("Flecs", "Flecs", "ecs_entity_component_room", ("ecs_entity_component",),
            "reference_only", "docs_confirm_cpp_ecs_performance_reference",
            "long_term_performance_reference_not_python_phase1", weights_req=False, rt_risk="low"),
    _review("Luna_dataclass_ECS_skeleton", "Luna ECS Skeleton", "ecs_entity_component_room", ("ecs_entity_component",),
            "candidate_for_near_term_adapter", "self_developed_primary_no_external_runtime",
            "implement_dataclass_ecs_skeleton", weights_req=False, structured=True, phase1=True, int_risk="low"),
    _review("NetworkX", "NetworkX", "semantic_event_graph_room", ("lightweight_semantic_event_graph",),
            "candidate_for_near_term_adapter", "docs_confirm_python_graph_modeling_json_serializable",
            "lightweight_event_graph_reference", graph=True, structured=True, edge="high", weights_req=False, phase1=True),
    _review("RDFLib", "RDFLib", "semantic_event_graph_room", ("lightweight_semantic_event_graph",),
            "reference_only", "rdf_triples_reference_not_mandatory_phase1",
            "kg_standard_reference_only", graph=True, weights_req=False),
    _review("Neo4j", "Neo4j", "semantic_event_graph_room", ("lightweight_semantic_event_graph",),
            "deferred_due_to_runtime_cost", "database_dependency_conflicts_lightweight_phase1",
            "no_database_phase1", graph=True, rt_risk="high", gov_risk="medium"),
    _review("Luna_lightweight_event_graph_skeleton", "Luna Event Graph Skeleton", "semantic_event_graph_room", ("lightweight_semantic_event_graph",),
            "candidate_for_near_term_adapter", "self_developed_lightweight_event_graph_primary",
            "implement_event_graph_skeleton", graph=True, structured=True, weights_req=False, phase1=True),
    _review("Luna_geometry_simulator", "Luna Geometry Simulator", "field_simulation_room", ("field_simulation",),
            "candidate_for_near_term_adapter", "self_developed_rules_geometry_state_machine_primary",
            "implement_simulation_placeholder", weights_req=False, spatial=True, phase1=True, int_risk="low"),
    _review("structured_LLM_reasoning", "Structured LLM Reasoning", "midplatform_reasoning_room", ("midplatform_reasoning",),
            "candidate_for_future_adapter", "requires_structured_io_and_non_execution_guard_not_yet_selected",
            "define_reasoning_schema_before_model_pick", structured=True, missing=["model_selection", "local_latency_confirmation"]),
    _review("local_small_model", "Local Small Model", "midplatform_reasoning_room", ("midplatform_reasoning",),
            "deferred_due_to_missing_outputs", "no_specific_local_model_selected",
            "evaluate_after_schema_defined", missing=["model_selection"]),
    _review("cloud_LLM", "Cloud LLM", "midplatform_reasoning_room", ("midplatform_reasoning",),
            "candidate_for_future_adapter", "structured_cloud_llm_possible_but_governance_latency_risk",
            "governance_review_before_cloud_adapter", gov_risk="medium", rt_risk="medium"),
    _review("rule_LLM_hybrid", "Rule + LLM Hybrid", "midplatform_reasoning_room", ("midplatform_reasoning",),
            "candidate_for_near_term_adapter", "hybrid_matches_field_first_structured_reasoning_design",
            "design_rule_layer_first_llm_explain_second", structured=True, phase1=True,
            candidates=["MidplatformReasoningCandidate"]),
    _review("Luna_frontend_sensing_adapter", "Luna Frontend Sensing Adapter", "source_intake_room", ("frontend_sensing",),
            "candidate_for_near_term_adapter", "self_developed_source_adapter_primary_for_multimodal_intake",
            "implement_source_adapter_metadata_normalization", weights_req=False, structured=True, phase1=True,
            candidates=["ObservationCandidate"], streaming=True, confidence=True),
    _review("Luna_drive_layer_self_work", "Luna Drive Layer Self-Work", "drive_layer_self_work", ("drive_layer",),
            "candidate_for_near_term_adapter", "survival_task_reflection_drive_remain_self_developed",
            "implement_drive_controllers_without_external_model_dependency", weights_req=False, phase1=True,
            candidates=["PerceptionRequestCandidate", "TaskControlCandidate"]),
)

OPERATION_NODES_COVERED: Tuple[str, ...] = (
    "frontend_sensing", "visual_object_segmentation_tracking", "ocr_text_perception",
    "audio_speech_speaker", "spatial_slam_dynamic_scene_graph", "ecs_entity_component",
    "lightweight_semantic_event_graph", "field_simulation", "midplatform_reasoning", "drive_layer",
)

DO_NOT_MISCLASSIFY: Tuple[str, ...] = (
    "document_review_not_model_download",
    "recommended_status_not_production_ready",
    "near_term_adapter_not_download_authorized",
    "reference_only_not_runtime_dependency",
    "review_not_midplatform_completed",
)

SELECTED_NEXT_PHASE = "Phase-Midplatform-Field-First-Core-Adapter-Priority-and-Download-Authorization-Planning-v1-001"
SELECTED_NEXT_ROUTE = "Adapter Priority and Download Authorization Planning"
