# -*- coding: utf-8 -*-
"""Hardware Camera Runtime Adapter Contract v1 — interface + method schemas only.

Phase-Hardware-Camera-Runtime-Adapter-Contract-v1-001
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

PHASE_ID = "Hardware-Camera-Runtime-Adapter-Contract-v1-001"
FINAL_DECISION = "READY_FOR_ADAPTER_IMPLEMENTATION_OR_GUARDEDTRIAL_PRECHECK"

REQUIRED_METHODS = [
    "open_camera",
    "close_camera",
    "capture_frame",
    "request_zoom",
    "request_autofocus",
    "request_exposure_adjustment",
    "request_stabilization",
    "get_capability_report",
    "get_health_status",
]

ERROR_TAXONOMY = [
    ("ADAPTER_MISSING", "no_adapter_implementation", "critical", "all_hardware_control", "install_adapter", "RUNTIME_ADAPTER_MISSING", False),
    ("CAMERA_OPEN_FAILED", "open_camera_failed", "high", "invoke_camera", "return_to_user_guidance", "CAMERA_UNAVAILABLE", True),
    ("CAMERA_PERMISSION_DENIED", "os_permission_denied", "high", "invoke_camera", "request_permission", "CAMERA_PERMISSION_DENIED", False),
    ("CAMERA_UNAVAILABLE", "camera_not_available", "high", "invoke_camera", "request_external_assistance", "CAMERA_UNAVAILABLE", False),
    ("CAMERA_TIMEOUT", "open_or_control_timeout", "medium", "invoke_camera", "timeout_fallback", "CAMERA_TIMEOUT", True),
    ("CAPTURE_TIMEOUT", "capture_frame_timeout", "medium", "capture_frame", "timeout_fallback", "FRAME_CAPTURE_FAILED", True),
    ("CAPTURE_FAILED", "capture_frame_failed", "high", "capture_frame", "return_to_user_guidance", "FRAME_CAPTURE_FAILED", True),
    ("ZOOM_UNSUPPORTED", "zoom_not_supported", "medium", "request_zoom", "skip_zoom_use_guidance", "ZOOM_UNSUPPORTED", False),
    ("AUTOFOCUS_UNSUPPORTED", "autofocus_not_supported", "medium", "request_autofocus", "manual_focus_guidance", "AUTOFOCUS_FAILED", False),
    ("AUTOFOCUS_FAILED", "autofocus_failed", "medium", "request_autofocus", "return_to_user_guidance", "AUTOFOCUS_FAILED", True),
    ("EXPOSURE_UNSUPPORTED", "exposure_not_supported", "medium", "request_exposure_adjustment", "lighting_guidance_only", "EXPOSURE_CONTROL_FAILED", False),
    ("STABILIZATION_UNSUPPORTED", "stabilization_not_supported", "low", "request_stabilization", "hold_still_guidance", "FRAME_CAPTURE_FAILED", False),
    ("FRAME_STALE", "frame_too_old_for_ocr", "medium", "ocrrequest_now", "recapture", "CAPABILITY_STALE", False),
    ("DEVICE_OVERHEAT", "thermal_limit", "high", "capture_frame", "safe_freeze", "DEVICE_OVERHEAT", False),
    ("BATTERY_LOW", "low_battery", "medium", "capture_frame", "reduce_capture_attempt", "BATTERY_LOW", False),
    ("UNKNOWN_ERROR", "unclassified_error", "medium", "runtime_hardware_action", "ask_user_manual_confirmation", "CAMERA_UNAVAILABLE", False),
]

METHOD_SPECS: Dict[str, Dict[str, Any]] = {
    "open_camera": {
        "request_schema": ["camera_id", "requested_mode", "permission_context"],
        "response_schema": ["opened", "camera_session_id", "error_code"],
        "timeout_policy": "default_open_camera_timeout_ms_placeholder",
        "retry_policy": "max_retry_count_placeholder",
        "permission_required": True,
        "allowed_status_outputs": ["opened", "permission_blocked"],
        "error_outputs": ["CAMERA_OPEN_FAILED", "CAMERA_PERMISSION_DENIED", "CAMERA_TIMEOUT"],
        "system_health_mapping_required": True,
    },
    "close_camera": {
        "request_schema": ["camera_session_id"],
        "response_schema": ["closed", "error_code"],
        "timeout_policy": "default_close_timeout_ms_placeholder",
        "retry_policy": "no_retry",
        "permission_required": False,
        "allowed_status_outputs": ["closed"],
        "error_outputs": ["UNKNOWN_ERROR"],
        "system_health_mapping_required": False,
    },
    "capture_frame": {
        "request_schema": ["camera_session_id", "capture_mode", "target_region_ref", "timeout_ms"],
        "response_schema": ["frame_ref", "frame_timestamp", "capture_status", "quality_placeholder", "error_code"],
        "timeout_policy": "default_capture_timeout_ms_placeholder",
        "retry_policy": "max_retry_count_placeholder",
        "permission_required": True,
        "allowed_status_outputs": ["captured", "failed", "timeout", "permission_blocked", "unsupported", "unknown"],
        "error_outputs": ["CAPTURE_TIMEOUT", "CAPTURE_FAILED", "CAMERA_PERMISSION_DENIED"],
        "system_health_mapping_required": True,
    },
    "request_zoom": {
        "request_schema": ["camera_session_id", "zoom_level_or_policy"],
        "response_schema": ["zoom_applied", "actual_zoom_placeholder", "error_code"],
        "timeout_policy": "default_control_timeout_ms_placeholder",
        "retry_policy": "limited_retry",
        "permission_required": False,
        "allowed_status_outputs": ["zoom_applied", "unsupported"],
        "error_outputs": ["ZOOM_UNSUPPORTED", "CAMERA_TIMEOUT"],
        "system_health_mapping_required": True,
    },
    "request_autofocus": {
        "request_schema": ["camera_session_id", "target_region_ref"],
        "response_schema": ["autofocus_applied", "focus_status", "error_code"],
        "timeout_policy": "default_control_timeout_ms_placeholder",
        "retry_policy": "max_retry_count_placeholder",
        "permission_required": False,
        "allowed_status_outputs": ["autofocus_applied", "failed", "unsupported"],
        "error_outputs": ["AUTOFOCUS_UNSUPPORTED", "AUTOFOCUS_FAILED", "CAMERA_TIMEOUT"],
        "system_health_mapping_required": True,
    },
    "request_exposure_adjustment": {
        "request_schema": ["camera_session_id", "exposure_policy"],
        "response_schema": ["exposure_applied", "exposure_status", "error_code"],
        "timeout_policy": "default_control_timeout_ms_placeholder",
        "retry_policy": "limited_retry",
        "permission_required": False,
        "allowed_status_outputs": ["exposure_applied", "unsupported"],
        "error_outputs": ["EXPOSURE_UNSUPPORTED", "CAMERA_TIMEOUT"],
        "system_health_mapping_required": True,
    },
    "request_stabilization": {
        "request_schema": ["camera_session_id", "stabilization_mode"],
        "response_schema": ["stabilization_applied", "stabilization_status", "error_code"],
        "timeout_policy": "default_control_timeout_ms_placeholder",
        "retry_policy": "no_retry",
        "permission_required": False,
        "allowed_status_outputs": ["stabilization_applied", "unsupported"],
        "error_outputs": ["STABILIZATION_UNSUPPORTED"],
        "system_health_mapping_required": False,
    },
    "get_capability_report": {
        "request_schema": ["hardware_profile_id", "camera_id"],
        "response_schema": ["capability_report_candidate", "capability_status", "stale_status", "error_code"],
        "timeout_policy": "default_report_timeout_ms_placeholder",
        "retry_policy": "no_retry",
        "permission_required": False,
        "allowed_status_outputs": ["unknown", "available", "unsupported", "degraded", "stale"],
        "error_outputs": ["ADAPTER_MISSING", "UNKNOWN_ERROR"],
        "system_health_mapping_required": True,
    },
    "get_health_status": {
        "request_schema": ["adapter_id", "camera_session_id"],
        "response_schema": ["health_status_candidate", "failure_class_candidate", "recovery_candidate", "error_code"],
        "timeout_policy": "default_report_timeout_ms_placeholder",
        "retry_policy": "no_retry",
        "permission_required": False,
        "allowed_status_outputs": ["healthy", "degraded", "unavailable", "permission_blocked", "timeout", "unknown"],
        "error_outputs": ["ADAPTER_MISSING", "UNKNOWN_ERROR"],
        "system_health_mapping_required": True,
    },
}

FOLLOWUPS = [
    "Hardware-Camera-Runtime-Adapter-Implementation-Stub-v1",
    "Hardware-Camera-Control-GuardedTrial-Precheck-v1",
    "Hardware-Profile-Capability-Registry-Review-v1",
    "Assisted-Static-Reading-GuardedTrial-v1",
    "Vision-Zoom-Autofocus-Resampling-Policy-v1",
    "OCRRequest-Gated-Submission-from-StaticReading-v1",
    "Confirmed-Text-Evidence-Memory-Governance-Contract-v1",
    "Emotional-Context-Background-Candidate-DryRun-v1",
]

LONG_TERM_TYPES = [
    "adapter_missing_observation_candidate",
    "adapter_error_observation_candidate",
    "repeated_camera_failure_candidate",
    "user_environment_context_candidate",
    "user_profile_context_candidate",
    "emotional_context_background_candidate",
]

TRACE_STEPS: List[Tuple[str, str, List[str], List[str], List[str]]] = [
    ("load_profile_registry", "registry_loaded", [], [], []),
    ("load_hardware_runtime_dryrun", "runtime_loaded", [], [], []),
    ("load_hardware_contract", "contract_loaded", [], [], []),
    ("define_adapter_interface", "interface_defined", [], [], []),
    ("define_method_schema", "methods_defined", [], [], ["invoke_adapter"]),
    ("define_capability_report_response_schema", "cap_report_schema", [], [], []),
    ("define_health_status_response_schema", "health_schema", [], [], []),
    ("define_frame_capture_response_schema", "frame_schema", [], [], ["capture_now"]),
    ("define_error_taxonomy", "errors", [], [], []),
    ("define_timeout_retry_permission_policy", "policy", [], [], []),
    ("define_guardedtrial_readiness_link", "gt_link", [], [], ["guardedtrial_now"]),
    ("generate_final_adapter_contract_decision", FINAL_DECISION, [], [], ["routing_change"]),
]


def _read_json(p: Path) -> Any:
    if p.is_file():
        return json.loads(p.read_text(encoding="utf-8"))
    return None


def _intake(roots: Dict[str, Path]) -> Dict[str, Any]:
    specs = [
        ("profile_registry", roots["registry"], "hardware_profile_capability_registry_v1_summary.json", False),
        ("hardware_runtime", roots["hw_rt"], "hardware_camera_control_runtime_dryrun_v1_summary.json", False),
        ("hardware_contract", roots["hw_contract"], "hardware_camera_control_contract_v1_summary.json", False),
        ("rrd_runtime", roots["rrd"], "static_readable_region_discovery_runtime_dryrun_v1_summary.json", False),
        ("bench", roots["bench"], None, False),
        ("health", roots["health"], None, False),
        ("sim", roots["sim"], None, False),
    ]
    rows = []
    for iid, root, art, optional in specs:
        loaded = root.is_dir()
        if art:
            loaded = loaded and (root / art).is_file()
        rows.append(
            {
                "intake_id": iid,
                "input_source": iid,
                "source_root_or_path": str(root),
                "artifact": art or "(directory)",
                "loaded": loaded,
                "optional": optional,
                "key_fields_observed": ["summary"] if loaded else [],
                "intake_status": "loaded" if loaded else "missing",
                "fact_status": "not_fact",
                "write_allowed": False,
            }
        )
    return {
        "schema_version": "hardware_camera_runtime_adapter_contract_input_intake_matrix_v1",
        "rows": rows,
        "fact_status": "not_fact",
        "write_allowed": False,
    }


def run_hardware_camera_runtime_adapter_contract_v1(
    *,
    hardware_profile_registry_root: str,
    hardware_runtime_root: str,
    hardware_contract_root: str,
    rrd_runtime_root: str,
    benchmark_smoke_root: str,
    system_health_root: str,
    simulation_root: str,
    workspace_root: Optional[str] = None,
) -> Dict[str, Any]:
    _ = workspace_root
    roots = {
        "registry": Path(hardware_profile_registry_root).resolve(),
        "hw_rt": Path(hardware_runtime_root).resolve(),
        "hw_contract": Path(hardware_contract_root).resolve(),
        "rrd": Path(rrd_runtime_root).resolve(),
        "bench": Path(benchmark_smoke_root).resolve(),
        "health": Path(system_health_root).resolve(),
        "sim": Path(simulation_root).resolve(),
    }

    method_rows = []
    for name in REQUIRED_METHODS:
        spec = METHOD_SPECS[name]
        method_rows.append(
            {
                "method_name": name,
                "request_schema": spec["request_schema"],
                "response_schema": spec["response_schema"],
                "timeout_policy": spec["timeout_policy"],
                "retry_policy": spec["retry_policy"],
                "permission_required": spec["permission_required"],
                "allowed_status_outputs": spec["allowed_status_outputs"],
                "error_outputs": spec["error_outputs"],
                "system_health_mapping_required": spec["system_health_mapping_required"],
                "method_invoked_now": False,
                "fact_status": "not_fact",
            }
        )

    error_rows = [
        {
            "error_code": code,
            "meaning": meaning,
            "severity_placeholder": sev,
            "blocked_action": blocked,
            "fallback_candidate": fb,
            "system_health_failure_class": health,
            "retry_allowed": retry,
            "fact_status": "not_fact",
        }
        for code, meaning, sev, blocked, fb, health, retry in ERROR_TAXONOMY
    ]

    error_to_failure = {r["error_code"]: r["system_health_failure_class"] for r in error_rows}
    failure_to_recovery: Dict[str, List[str]] = {
        "RUNTIME_ADAPTER_MISSING": ["INSTALL_RUNTIME_ADAPTER", "FALLBACK_USER_GUIDANCE"],
        "CAMERA_PERMISSION_DENIED": ["REQUEST_PERMISSION", "FALLBACK_USER_GUIDANCE"],
        "CAMERA_UNAVAILABLE": ["FALLBACK_EXTERNAL_ASSISTANCE", "DEGRADED_MODE"],
        "CAMERA_TIMEOUT": ["FALLBACK_USER_GUIDANCE", "REDUCE_CAPTURE_ATTEMPT"],
        "FRAME_CAPTURE_FAILED": ["FALLBACK_USER_GUIDANCE", "FALLBACK_EXTERNAL_ASSISTANCE"],
        "ZOOM_UNSUPPORTED": ["FALLBACK_USER_GUIDANCE"],
        "AUTOFOCUS_FAILED": ["FALLBACK_USER_GUIDANCE"],
        "EXPOSURE_CONTROL_FAILED": ["FALLBACK_USER_GUIDANCE"],
        "DEVICE_OVERHEAT": ["SAFE_FREEZE"],
        "BATTERY_LOW": ["REDUCE_CAPTURE_ATTEMPT"],
    }

    guardedtrial_blockers = [
        "adapter_implementation_missing",
        "real_permission_state_unknown",
    ]

    trace_steps = [
        {
            "step_id": sid,
            "step_name": sid,
            "decision": decision,
            "reason_codes": reasons,
            "allowed_next_actions": allowed,
            "blocked_next_actions": blocked,
            "runtime_action_committed": False,
        }
        for sid, decision, reasons, allowed, blocked in TRACE_STEPS
    ]

    return {
        "summary": {
            "schema_version": "hardware_camera_runtime_adapter_contract_v1_summary_v0",
            "phase": PHASE_ID,
            "contract_scope": "hardware_camera_runtime_adapter_contract_only",
            "based_on_hardware_profile_registry": roots["registry"].is_dir(),
            "based_on_hardware_runtime_dryrun": roots["hw_rt"].is_dir(),
            "based_on_hardware_control_contract": roots["hw_contract"].is_dir(),
            "adapter_interface_defined": True,
            "required_methods_defined": True,
            "method_request_response_schema_defined": True,
            "capability_report_response_schema_defined": True,
            "health_status_response_schema_defined": True,
            "frame_capture_response_schema_defined": True,
            "hardware_error_taxonomy_defined": True,
            "timeout_retry_permission_policy_defined": True,
            "system_health_mapping_defined": True,
            "guardedtrial_readiness_link_defined": True,
            "adapter_implementation_available": False,
            "adapter_invoked": False,
            "hardware_probe_invoked": False,
            "runtime_camera_invoked": False,
            "runtime_frame_captured": False,
            "hardware_action_invoked": False,
            "zoom_invoked": False,
            "autofocus_invoked": False,
            "exposure_control_invoked": False,
            "stabilization_invoked": False,
            "detector_invoked": False,
            "ocr_invoked": False,
            "ocrrequest_generated": False,
            "midplatform_fact_written": False,
            "hardware_fact_written": False,
            "world_model_written": False,
            "scene_delta_candidate_generated": False,
            "fact_status": "not_fact",
            "write_allowed": False,
            "phase_verdict_hint": "GO",
        },
        "intake": _intake(roots),
        "interface": {
            "schema_version": "hardware_camera_runtime_adapter_interface_contract_v1",
            "adapter_id": "luna_camera_runtime_adapter_v1",
            "adapter_version": "v1_contract_only",
            "adapter_status": "contract_only",
            "implementation_required_later": True,
            "required_methods": REQUIRED_METHODS,
            "adapter_invoked_now": False,
            "implementation_available": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "method_schema": {
            "schema_version": "hardware_camera_runtime_adapter_method_schema_v1",
            "methods": method_rows,
            "required_method_count": len(REQUIRED_METHODS),
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "capability_response_schema": {
            "schema_version": "hardware_camera_adapter_capability_report_response_schema_v1",
            "field_definitions": [
                "capability_report_response_id",
                "hardware_profile_id",
                "camera_id",
                "camera_available_status",
                "zoom_supported_status",
                "autofocus_supported_status",
                "exposure_control_supported_status",
                "stabilization_supported_status",
                "frame_capture_supported_status",
                "still_frame_supported_status",
                "torch_or_light_supported_status",
                "depth_or_tof_supported_status",
                "capability_status",
                "stale_status",
                "confidence_placeholder",
                "source",
            ],
            "example": {
                "capability_report_response_id": "cap_resp_schema_example",
                "hardware_profile_id": "unknown_placeholder",
                "camera_id": "primary_rgb_unknown",
                "camera_available_status": "unknown",
                "zoom_supported_status": "unknown",
                "autofocus_supported_status": "unknown",
                "exposure_control_supported_status": "unknown",
                "stabilization_supported_status": "unknown",
                "frame_capture_supported_status": "unknown",
                "still_frame_supported_status": "unknown",
                "torch_or_light_supported_status": "unknown",
                "depth_or_tof_supported_status": "unknown",
                "capability_status": "unknown",
                "stale_status": "unknown",
                "confidence_placeholder": "unknown",
                "source": "runtime_adapter_candidate",
                "fact_status": "not_fact",
            },
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "health_response_schema": {
            "schema_version": "hardware_camera_adapter_health_status_response_schema_v1",
            "field_definitions": [
                "health_status_response_id",
                "adapter_id",
                "camera_session_id",
                "status",
                "failure_class_candidate",
                "recovery_candidate",
                "system_health_report_required",
            ],
            "allowed_status_values": [
                "healthy", "degraded", "unavailable", "permission_blocked", "timeout", "unknown",
            ],
            "example": {
                "health_status_response_id": "health_resp_schema_example",
                "adapter_id": "luna_camera_runtime_adapter_v1",
                "camera_session_id": "session_placeholder",
                "status": "unknown",
                "failure_class_candidate": "HARDWARE_CAPABILITY_UNKNOWN",
                "recovery_candidate": "FALLBACK_USER_GUIDANCE",
                "system_health_report_required": True,
                "fact_status": "not_fact",
            },
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "frame_response_schema": {
            "schema_version": "hardware_camera_adapter_frame_capture_response_schema_v1",
            "field_definitions": [
                "frame_capture_response_id",
                "camera_session_id",
                "frame_ref",
                "frame_timestamp",
                "frame_source",
                "target_region_ref",
                "capture_status",
                "quality_placeholder",
                "stc_anchor_required",
                "frame_is_fact",
            ],
            "allowed_capture_status": [
                "captured", "failed", "timeout", "permission_blocked", "unsupported", "unknown",
            ],
            "example": {
                "frame_capture_response_id": "frame_resp_schema_example",
                "camera_session_id": "session_placeholder",
                "frame_ref": "frame_ref_placeholder_not_real",
                "frame_timestamp": "not_set",
                "frame_source": "adapter_candidate_only",
                "target_region_ref": "rrc_placeholder",
                "capture_status": "unknown",
                "quality_placeholder": "unknown",
                "stc_anchor_required": True,
                "frame_is_fact": False,
                "fact_status": "not_fact",
            },
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "error_taxonomy": {
            "schema_version": "hardware_camera_adapter_error_taxonomy_v1",
            "errors": error_rows,
            "error_count": len(error_rows),
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "timeout_policy": {
            "schema_version": "hardware_camera_adapter_timeout_retry_permission_policy_v1",
            "default_open_camera_timeout_ms_placeholder": 5000,
            "default_capture_timeout_ms_placeholder": 8000,
            "max_retry_count_placeholder": 2,
            "retry_allowed_errors": ["CAMERA_TIMEOUT", "CAPTURE_TIMEOUT", "AUTOFOCUS_FAILED"],
            "retry_forbidden_errors": ["CAMERA_PERMISSION_DENIED", "ADAPTER_MISSING", "ZOOM_UNSUPPORTED"],
            "permission_required_methods": ["open_camera", "capture_frame"],
            "permission_denied_fallback": "request_permission_or_external_assistance",
            "timeout_fallback": "return_to_user_guidance",
            "repeated_failure_policy": "stop_internal_retry_then_external_assistance",
            "runtime_enforced_now": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "health_mapping": {
            "schema_version": "hardware_camera_adapter_system_health_mapping_v1",
            "system_health_governance_available": roots["health"].is_dir(),
            "error_to_failure_class_mapping": error_to_failure,
            "failure_class_to_recovery_mapping": failure_to_recovery,
            "module_health_report_required_later": True,
            "module_health_report_generated_now": False,
            "recovery_action_committed_now": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "guardedtrial_link": {
            "schema_version": "hardware_camera_adapter_guardedtrial_readiness_link_v1",
            "guardedtrial_readiness_link_defined": True,
            "guardedtrial_allowed_now": False,
            "guardedtrial_allowed_later": True,
            "required_before_guardedtrial": [
                "adapter_contract_defined",
                "adapter_implementation_available",
                "capability_registry_available",
                "permission_policy_defined",
                "system_health_mapping_defined",
                "fallback_policy_defined",
                "no_write_boundary_passed",
            ],
            "current_blockers": guardedtrial_blockers,
            "guardedtrial_invoked_now": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "ocr_gate": {
            "schema_version": "hardware_camera_adapter_ocrrequest_gate_link_v1",
            "static_capture_result_required": True,
            "frame_capture_response_required": True,
            "capture_status_must_be_captured": True,
            "stc_anchor_required": True,
            "capture_quality_required": True,
            "ocrrequest_eligible_later": True,
            "ocrrequest_eligible_now": False,
            "ocrrequest_generated_now": False,
            "provider_invoked_now": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "long_term": {
            "schema_version": "hardware_camera_adapter_long_term_candidate_link_v1",
            "can_feed_long_term_candidate": True,
            "candidate_types": LONG_TERM_TYPES,
            "cannot_write_fact": True,
            "cannot_write_profile_now": True,
            "write_allowed_now": False,
            "required_metadata": [
                "source_chain",
                "time_anchor",
                "adapter_ref",
                "method_name",
                "error_or_missing_reason",
                "privacy_sensitivity",
                "future_usage_scope",
            ],
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "trace": {
            "schema_version": "hardware_camera_runtime_adapter_contract_decision_trace_v1",
            "steps": trace_steps,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "final": {
            "schema_version": "hardware_camera_runtime_adapter_contract_final_decision_v1",
            "final_decision": FINAL_DECISION,
            "adapter_contract_defined": True,
            "adapter_implementation_available": False,
            "guardedtrial_allowed_now": False,
            "guardedtrial_allowed_later": True,
            "recommended_next_phase": "Hardware-Camera-Runtime-Adapter-Implementation-Stub-v1",
            "alternate_next_phase": "Hardware-Camera-Control-GuardedTrial-Precheck-v1",
            "alternate_next_phase_2": "Assisted-Static-Reading-GuardedTrial-v1",
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "boundary": {
            "schema_version": "hardware_camera_runtime_adapter_contract_boundary_report_v1",
            "adapter_contract_only": True,
            "adapter_invoked": False,
            "hardware_probe_invoked": False,
            "runtime_camera_invoked": False,
            "runtime_frame_captured": False,
            "hardware_action_invoked": False,
            "zoom_invoked": False,
            "autofocus_invoked": False,
            "exposure_control_invoked": False,
            "stabilization_invoked": False,
            "detector_invoked": False,
            "ocr_invoked": False,
            "ocrrequest_generated": False,
            "midplatform_fact_written": False,
            "hardware_fact_written": False,
            "world_model_written": False,
            "scene_delta_candidate_generated": False,
            "fact_status": "not_fact",
        },
        "metrics": {
            "schema_version": "hardware_camera_runtime_adapter_contract_metrics_candidate_report_v1",
            "required_method_count": len(REQUIRED_METHODS),
            "error_taxonomy_count": len(error_rows),
            "guardedtrial_current_blocker_count": len(guardedtrial_blockers),
            "adapter_invoked_count": 0,
            "hardware_probe_invoked_count": 0,
            "hardware_action_invoked_count": 0,
            "fact_write_allowed_count": 0,
            "no_write_boundary_pass_rate": 1.0,
            "benchmark_score_generated": False,
            "provider_comparison_claimed": False,
        },
        "benchmark_link": {
            "schema_version": "hardware_camera_runtime_adapter_contract_benchmark_link_report_v1",
            "benchmark_real_values_smoke_available": roots["bench"].is_dir(),
            "current_phase_updates_benchmark_values": False,
            "current_phase_collects_t2": False,
            "ground_truth_available": False,
            "benchmark_score_generated": False,
            "provider_comparison_claimed": False,
        },
        "health_report": {
            "schema_version": "hardware_camera_runtime_adapter_contract_system_health_report_v1",
            "system_health_governance_available": roots["health"].is_dir(),
            "module_health_report_candidate_generated": False,
            "provider_health_runtime_checked": False,
            "recovery_action_committed": False,
            "capability_mask_consumed": False,
            "no_runtime_health_claim": True,
        },
        "no_write": {
            "schema_version": "hardware_camera_runtime_adapter_contract_no_write_boundary_report_v1",
            "boundary_ok": True,
            "violations": [],
            "adapter_contract_only": True,
            "adapter_invoked": False,
            "hardware_probe_invoked": False,
            "runtime_camera_invoked": False,
            "runtime_frame_captured": False,
            "hardware_action_invoked": False,
            "zoom_invoked": False,
            "autofocus_invoked": False,
            "exposure_control_invoked": False,
            "stabilization_invoked": False,
            "detector_invoked": False,
            "ocr_invoked": False,
            "ocrrequest_generated": False,
            "midplatform_fact_written": False,
            "hardware_fact_written": False,
            "scene_delta_written": False,
            "world_model_written": False,
            "benchmark_result_claimed": False,
            "provider_comparison_claimed": False,
            "production_readiness_claimed": False,
        },
        "sim_report": {
            "schema_version": "hardware_camera_runtime_adapter_contract_simulation_context_report_v1",
            "simulation_profile_id": "developer_full",
            "simulation_context_available": roots["sim"].is_dir(),
            "run_model": False,
            "simulation_context_only": True,
            "runtime_routing_changed": False,
            "ci_default_changed": False,
            "no_hardware_certification_claim": True,
        },
        "non_claims": {
            "schema_version": "hardware_camera_runtime_adapter_contract_non_claims_report_v1",
            "claims": [
                "no_adapter_implementation",
                "no_real_camera_invocation",
                "method_schema_not_hardware_action",
                "frame_response_not_capture",
                "capability_response_not_hardware_fact",
                "health_response_not_health_commit",
                "guardedtrial_later_not_authorization_now",
                "no_ocr_no_ocrrequest",
                "no_world_model_write",
                "no_scene_delta",
                "not_production_ready",
            ],
        },
        "followups": {
            "schema_version": "hardware_camera_runtime_adapter_contract_open_followups_v1",
            "items": FOLLOWUPS,
        },
        "audit": {
            "schema_version": "hardware_camera_runtime_adapter_contract_audit_report_v1",
            "hardware_camera_runtime_adapter_contract_v1_executed": True,
            "adapter_contract_only": True,
            "adapter_interface_defined": True,
            "required_methods_defined": True,
            "method_request_response_schema_defined": True,
            "capability_report_response_schema_defined": True,
            "health_status_response_schema_defined": True,
            "frame_capture_response_schema_defined": True,
            "hardware_error_taxonomy_defined": True,
            "timeout_retry_permission_policy_defined": True,
            "system_health_mapping_defined": True,
            "guardedtrial_readiness_link_defined": True,
            "adapter_implementation_available": False,
            "adapter_invoked": False,
            "hardware_probe_invoked": False,
            "runtime_camera_invoked": False,
            "runtime_frame_captured": False,
            "hardware_action_invoked": False,
            "zoom_invoked": False,
            "autofocus_invoked": False,
            "exposure_control_invoked": False,
            "stabilization_invoked": False,
            "detector_invoked": False,
            "ocr_invoked": False,
            "ocrrequest_generated": False,
            "midplatform_fact_written": False,
            "hardware_fact_written": False,
            "scene_delta_candidate_generated": False,
            "world_model_written": False,
            "benchmark_result_claimed": False,
            "provider_comparison_claimed": False,
            "production_readiness_claimed": False,
        },
    }
