# -*- coding: utf-8 -*-
"""Hardware Profile Capability Registry v1 — schema + minimal unknown profile only.

Phase-Hardware-Profile-Capability-Registry-v1-001
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

PHASE_ID = "Hardware-Profile-Capability-Registry-v1-001"
FINAL_DECISION = "READY_FOR_PROFILE_REGISTRY_REVIEW_OR_ADAPTER_IMPLEMENTATION"

CAPABILITY_STATUSES = [
    "available",
    "unavailable",
    "unknown",
    "unsupported",
    "degraded",
    "stale",
    "permission_blocked",
    "runtime_adapter_missing",
    "conflict",
]

SENSOR_TYPES = ["rgb_camera", "depth_tof", "imu", "gps", "microphone", "light_sensor"]

STATUS_META: Dict[str, Dict[str, Any]] = {
    "available": {
        "meaning": "capability_confirmed_for_profile",
        "allowed_runtime_action": ["guarded_capture_with_adapter"],
        "blocked_runtime_action": [],
        "fallback_required": False,
        "system_health_required": False,
    },
    "unavailable": {
        "meaning": "capability_absent_on_device",
        "allowed_runtime_action": [],
        "blocked_runtime_action": ["invoke_camera", "request_zoom", "request_autofocus"],
        "fallback_required": True,
        "system_health_required": True,
    },
    "unknown": {
        "meaning": "capability_not_probed_not_asserted",
        "allowed_runtime_action": [],
        "blocked_runtime_action": ["invoke_camera", "force_hardware_action"],
        "fallback_required": True,
        "system_health_required": False,
    },
    "unsupported": {
        "meaning": "device_does_not_support_feature",
        "allowed_runtime_action": [],
        "blocked_runtime_action": ["request_zoom", "request_autofocus", "request_exposure_adjustment"],
        "fallback_required": True,
        "system_health_required": False,
    },
    "degraded": {
        "meaning": "capability_limited_or_reduced",
        "allowed_runtime_action": ["degraded_capture_only"],
        "blocked_runtime_action": ["high_zoom", "burst_capture"],
        "fallback_required": True,
        "system_health_required": True,
    },
    "stale": {
        "meaning": "profile_outdated",
        "allowed_runtime_action": ["profile_review"],
        "blocked_runtime_action": ["runtime_hardware_action"],
        "fallback_required": True,
        "system_health_required": True,
    },
    "permission_blocked": {
        "meaning": "os_permission_denied_or_unknown",
        "allowed_runtime_action": [],
        "blocked_runtime_action": ["invoke_camera"],
        "fallback_required": True,
        "system_health_required": True,
    },
    "runtime_adapter_missing": {
        "meaning": "no_adapter_to_execute_control",
        "allowed_runtime_action": [],
        "blocked_runtime_action": ["all_hardware_control"],
        "fallback_required": True,
        "system_health_required": True,
    },
    "conflict": {
        "meaning": "conflicting_capability_reports",
        "allowed_runtime_action": [],
        "blocked_runtime_action": ["runtime_hardware_action"],
        "fallback_required": True,
        "system_health_required": True,
    },
}

HEALTH_CLASSES = [
    "HARDWARE_PROFILE_MISSING",
    "CAPABILITY_REGISTRY_MISSING",
    "RUNTIME_ADAPTER_MISSING",
    "CAMERA_PERMISSION_UNKNOWN",
    "CAPABILITY_STALE",
    "CAPABILITY_CONFLICT",
]

HEALTH_RECOVERY = [
    "REGISTER_PROFILE",
    "INSTALL_RUNTIME_ADAPTER",
    "REQUEST_PERMISSION",
    "FALLBACK_USER_GUIDANCE",
    "FALLBACK_EXTERNAL_ASSISTANCE",
]

FOLLOWUPS = [
    "Hardware-Camera-Runtime-Adapter-Contract-v1",
    "Hardware-Profile-Capability-Registry-Review-v1",
    "Hardware-Camera-Control-GuardedTrial-v1",
    "Assisted-Static-Reading-GuardedTrial-v1",
    "Vision-Zoom-Autofocus-Resampling-Policy-v1",
    "OCRRequest-Gated-Submission-from-StaticReading-v1",
    "Confirmed-Text-Evidence-Memory-Governance-Contract-v1",
    "Emotional-Context-Background-Candidate-DryRun-v1",
]

LONG_TERM_TYPES = [
    "hardware_profile_missing_observation_candidate",
    "capability_registry_missing_observation_candidate",
    "runtime_adapter_missing_observation_candidate",
    "repeated_hardware_unavailable_candidate",
    "user_environment_context_candidate",
    "user_profile_context_candidate",
    "emotional_context_background_candidate",
]

TRACE_STEPS: List[Tuple[str, str, List[str], List[str], List[str]]] = [
    ("load_hardware_runtime_dryrun", "runtime_loaded", [], [], []),
    ("load_hardware_contract", "contract_loaded", [], [], []),
    ("define_hardware_profile_schema", "profile_schema", [], [], []),
    ("define_camera_capability_registry_schema", "camera_schema", [], [], []),
    ("define_device_registry_schema", "device_schema", [], [], []),
    ("define_sensor_registry_schema", "sensor_schema", [], [], []),
    ("define_capability_status_enum", "status_enum", [], [], []),
    ("generate_minimal_unknown_profile", "unknown_profile", [], [], ["probe_hardware"]),
    ("define_runtime_adapter_placeholder", "adapter_placeholder", [], [], ["invoke_adapter"]),
    ("define_profile_freshness_policy", "freshness", [], [], []),
    ("define_guardedtrial_precondition_link", "guardedtrial_link", [], [], ["guardedtrial_now"]),
    ("generate_final_registry_decision", FINAL_DECISION, [], [], ["routing_change"]),
]


def _read_json(p: Path) -> Any:
    if p.is_file():
        return json.loads(p.read_text(encoding="utf-8"))
    return None


def _intake(roots: Dict[str, Path]) -> Dict[str, Any]:
    specs = [
        ("hardware_runtime", roots["hw_rt"], "hardware_camera_control_runtime_dryrun_v1_summary.json", False),
        ("hardware_contract", roots["hw_contract"], "hardware_camera_control_contract_v1_summary.json", False),
        ("rrd_runtime", roots["rrd"], "static_readable_region_discovery_runtime_dryrun_v1_summary.json", False),
        ("bench", roots["bench"], None, False),
        ("health", roots["health"], None, False),
        ("sim", roots["sim"], None, False),
    ]
    rows = []
    for iid, root, art, optional in specs:
        loaded = root.is_dir()
        if art:
            loaded = loaded and (root / art).is_file()
        rows.append(
            {
                "intake_id": iid,
                "input_source": iid,
                "source_root_or_path": str(root),
                "artifact": art or "(directory)",
                "loaded": loaded,
                "optional": optional,
                "key_fields_observed": ["summary"] if loaded else [],
                "intake_status": "loaded" if loaded else "missing",
                "fact_status": "not_fact",
                "write_allowed": False,
            }
        )
    return {
        "schema_version": "hardware_profile_registry_input_intake_matrix_v1",
        "rows": rows,
        "fact_status": "not_fact",
        "write_allowed": False,
    }


def run_hardware_profile_capability_registry_v1(
    *,
    hardware_runtime_root: str,
    hardware_contract_root: str,
    rrd_runtime_root: str,
    benchmark_smoke_root: str,
    system_health_root: str,
    simulation_root: str,
    workspace_root: Optional[str] = None,
) -> Dict[str, Any]:
    _ = workspace_root
    roots = {
        "hw_rt": Path(hardware_runtime_root).resolve(),
        "hw_contract": Path(hardware_contract_root).resolve(),
        "rrd": Path(rrd_runtime_root).resolve(),
        "bench": Path(benchmark_smoke_root).resolve(),
        "health": Path(system_health_root).resolve(),
        "sim": Path(simulation_root).resolve(),
    }

    status_enum_rows = [
        {
            "status": st,
            **STATUS_META[st],
            "fact_status": "not_fact",
        }
        for st in CAPABILITY_STATUSES
    ]

    trace_steps = [
        {
            "step_id": sid,
            "step_name": sid,
            "decision": decision,
            "reason_codes": reasons,
            "allowed_next_actions": allowed,
            "blocked_next_actions": blocked,
            "runtime_action_committed": False,
        }
        for sid, decision, reasons, allowed, blocked in TRACE_STEPS
    ]

    guardedtrial_blockers = [
        "capability_registry_missing",
        "runtime_adapter_missing",
    ]

    return {
        "summary": {
            "schema_version": "hardware_profile_capability_registry_v1_summary_v0",
            "phase": PHASE_ID,
            "registry_scope": "hardware_profile_capability_registry_schema_only",
            "based_on_hardware_runtime_dryrun": roots["hw_rt"].is_dir(),
            "based_on_hardware_contract": roots["hw_contract"].is_dir(),
            "hardware_profile_schema_defined": True,
            "camera_capability_registry_schema_defined": True,
            "device_registry_schema_defined": True,
            "sensor_registry_schema_defined": True,
            "capability_status_enum_defined": True,
            "minimal_unknown_profile_generated": True,
            "runtime_adapter_placeholder_defined": True,
            "profile_freshness_policy_defined": True,
            "system_health_link_defined": True,
            "guardedtrial_precondition_link_defined": True,
            "hardware_probe_invoked": False,
            "runtime_camera_invoked": False,
            "runtime_frame_captured": False,
            "hardware_action_invoked": False,
            "zoom_invoked": False,
            "autofocus_invoked": False,
            "exposure_control_invoked": False,
            "stabilization_invoked": False,
            "detector_invoked": False,
            "ocr_invoked": False,
            "ocrrequest_generated": False,
            "midplatform_fact_written": False,
            "hardware_fact_written": False,
            "world_model_written": False,
            "scene_delta_candidate_generated": False,
            "fact_status": "not_fact",
            "write_allowed": False,
            "phase_verdict_hint": "GO",
        },
        "intake": _intake(roots),
        "profile_schema": {
            "schema_version": "hardware_profile_schema_v1",
            "field_definitions": [
                "hardware_profile_id",
                "device_class",
                "camera_stack_type",
                "primary_camera_id",
                "supported_sensor_refs",
                "supported_control_refs",
                "runtime_adapter_ref",
                "capability_report_ref",
                "profile_source",
                "profile_freshness_status",
                "created_at_placeholder",
                "updated_at_placeholder",
            ],
            "example": {
                "hardware_profile_id": "unknown_placeholder",
                "device_class": "mobile_handheld",
                "camera_stack_type": "unknown",
                "primary_camera_id": "primary_rgb_unknown",
                "supported_sensor_refs": [],
                "supported_control_refs": [],
                "runtime_adapter_ref": "adapter_missing_placeholder",
                "capability_report_ref": "cap_unknown_placeholder",
                "profile_source": "registry_schema_only",
                "profile_freshness_status": "unknown",
                "created_at_placeholder": "not_set",
                "updated_at_placeholder": "not_set",
                "fact_status": "not_fact",
                "write_allowed": False,
            },
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "camera_schema": {
            "schema_version": "camera_capability_registry_schema_v1",
            "field_definitions": [
                "camera_capability_id",
                "camera_id",
                "camera_available",
                "frame_capture_supported",
                "still_frame_supported",
                "zoom_supported",
                "autofocus_supported",
                "exposure_control_supported",
                "stabilization_supported",
                "torch_or_light_supported",
                "depth_or_tof_supported",
                "max_resolution_placeholder",
                "max_fps_placeholder",
                "focus_mode_placeholder",
                "zoom_range_placeholder",
                "capability_status",
                "capability_confidence_placeholder",
                "capability_source",
                "stale_policy",
            ],
            "example": {
                "camera_capability_id": "cap_unknown_placeholder",
                "camera_id": "primary_rgb_unknown",
                "camera_available": "unknown",
                "frame_capture_supported": "unknown",
                "still_frame_supported": "unknown",
                "zoom_supported": "unknown",
                "autofocus_supported": "unknown",
                "exposure_control_supported": "unknown",
                "stabilization_supported": "unknown",
                "torch_or_light_supported": "unknown",
                "depth_or_tof_supported": "unknown",
                "max_resolution_placeholder": None,
                "max_fps_placeholder": None,
                "focus_mode_placeholder": "unknown",
                "zoom_range_placeholder": None,
                "capability_status": "unknown",
                "capability_confidence_placeholder": "unknown",
                "capability_source": "registry_schema_only_not_probe",
                "stale_policy": "refresh_before_guarded_trial",
                "fact_status": "not_fact",
                "write_allowed": False,
            },
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "device_schema": {
            "schema_version": "device_registry_schema_v1",
            "field_definitions": [
                "device_id",
                "device_type",
                "os_type",
                "permission_state_placeholder",
                "camera_permission_required",
                "microphone_permission_required",
                "power_state_placeholder",
                "thermal_state_placeholder",
                "network_state_placeholder",
                "runtime_adapter_available",
                "profile_status",
            ],
            "example": {
                "device_id": "device_unknown_placeholder",
                "device_type": "unknown",
                "os_type": "unknown",
                "permission_state_placeholder": "unknown",
                "camera_permission_required": True,
                "microphone_permission_required": False,
                "power_state_placeholder": "unknown",
                "thermal_state_placeholder": "unknown",
                "network_state_placeholder": "unknown",
                "runtime_adapter_available": False,
                "profile_status": "unknown",
                "fact_status": "not_fact",
                "write_allowed": False,
            },
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "sensor_schema": {
            "schema_version": "sensor_registry_schema_v1",
            "sensor_types": SENSOR_TYPES,
            "field_definitions": [
                "sensor_id",
                "sensor_type",
                "availability_status",
                "capability_status",
                "runtime_adapter_ref",
                "sample_rate_placeholder",
                "freshness_policy",
            ],
            "examples": [
                {
                    "sensor_id": f"sensor_{st}_unknown",
                    "sensor_type": st,
                    "availability_status": "unknown",
                    "capability_status": "unknown",
                    "runtime_adapter_ref": "adapter_missing_placeholder",
                    "sample_rate_placeholder": None,
                    "freshness_policy": "refresh_before_guarded_trial",
                    "fact_status": "not_fact",
                }
                for st in SENSOR_TYPES
            ],
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "status_enum": {
            "schema_version": "hardware_capability_status_enum_v1",
            "statuses": status_enum_rows,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "unknown_profile": {
            "schema_version": "hardware_minimal_unknown_profile_v1",
            "hardware_profile_id": "unknown_placeholder",
            "camera_available": "unknown",
            "zoom_supported": "unknown",
            "autofocus_supported": "unknown",
            "exposure_control_supported": "unknown",
            "stabilization_supported": "unknown",
            "frame_capture_supported": "unknown",
            "still_frame_supported": "unknown",
            "runtime_adapter_available": False,
            "capability_status": "unknown",
            "capability_unknown_allowed": True,
            "usable_for_runtime_action": False,
            "usable_for_guardedtrial_precondition": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "adapter_placeholder": {
            "schema_version": "hardware_camera_runtime_adapter_placeholder_v1",
            "runtime_adapter_placeholder_defined": True,
            "adapter_id": "luna_camera_runtime_adapter_v0_missing",
            "adapter_status": "missing_placeholder",
            "required_methods": [
                "open_camera",
                "close_camera",
                "capture_frame",
                "request_zoom",
                "request_autofocus",
                "request_exposure_adjustment",
                "request_stabilization",
                "get_capability_report",
                "get_health_status",
            ],
            "implementation_available": False,
            "runtime_invoked_now": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "freshness_policy": {
            "schema_version": "hardware_profile_freshness_stale_policy_v1",
            "freshness_policy_defined": True,
            "stale_blocks_runtime_action": True,
            "stale_allows_profile_review": True,
            "stale_allows_long_term_candidate": True,
            "capability_conflict_requires_review": True,
            "runtime_action_allowed_when_stale": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "health_link": {
            "schema_version": "hardware_profile_registry_system_health_link_v1",
            "system_health_governance_available": roots["health"].is_dir(),
            "health_classes": HEALTH_CLASSES,
            "recovery_candidates": HEALTH_RECOVERY,
            "recovery_action_committed_now": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "guardedtrial_link": {
            "schema_version": "hardware_profile_registry_guardedtrial_precondition_link_v1",
            "guardedtrial_precondition_link_defined": True,
            "guardedtrial_allowed_now": False,
            "guardedtrial_allowed_later": True,
            "required_before_guardedtrial": [
                "hardware_profile_available_or_unknown_explicitly_handled",
                "camera_capability_registry_available",
                "runtime_adapter_available",
                "system_health_link_available",
                "fallback_policy_available",
                "no_write_boundary_passed",
            ],
            "current_blockers": guardedtrial_blockers,
            "guardedtrial_invoked_now": False,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "long_term": {
            "schema_version": "hardware_profile_registry_long_term_candidate_link_v1",
            "can_feed_long_term_candidate": True,
            "candidate_types": LONG_TERM_TYPES,
            "cannot_write_fact": True,
            "cannot_write_profile_now": True,
            "write_allowed_now": False,
            "required_metadata": [
                "source_chain",
                "time_anchor",
                "hardware_profile_ref",
                "missing_or_unknown_reason",
                "capability_status",
                "privacy_sensitivity",
                "future_usage_scope",
            ],
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "trace": {
            "schema_version": "hardware_profile_registry_decision_trace_v1",
            "steps": trace_steps,
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "final": {
            "schema_version": "hardware_profile_registry_final_decision_v1",
            "final_decision": FINAL_DECISION,
            "minimal_unknown_profile_generated": True,
            "guardedtrial_allowed_now": False,
            "guardedtrial_allowed_later": True,
            "recommended_next_phase": "Hardware-Camera-Runtime-Adapter-Contract-v1",
            "alternate_next_phase": "Hardware-Profile-Capability-Registry-Review-v1",
            "alternate_next_phase_2": "Assisted-Static-Reading-GuardedTrial-v1",
            "fact_status": "not_fact",
            "write_allowed": False,
        },
        "boundary": {
            "schema_version": "hardware_profile_registry_boundary_report_v1",
            "registry_schema_only": True,
            "hardware_probe_invoked": False,
            "runtime_camera_invoked": False,
            "runtime_frame_captured": False,
            "hardware_action_invoked": False,
            "zoom_invoked": False,
            "autofocus_invoked": False,
            "exposure_control_invoked": False,
            "stabilization_invoked": False,
            "detector_invoked": False,
            "ocr_invoked": False,
            "ocrrequest_generated": False,
            "midplatform_fact_written": False,
            "hardware_fact_written": False,
            "world_model_written": False,
            "scene_delta_candidate_generated": False,
            "fact_status": "not_fact",
        },
        "metrics": {
            "schema_version": "hardware_profile_registry_metrics_candidate_report_v1",
            "schema_defined_count": 4,
            "capability_status_enum_count": len(CAPABILITY_STATUSES),
            "minimal_unknown_profile_count": 1,
            "runtime_adapter_placeholder_count": 1,
            "guardedtrial_current_blocker_count": len(guardedtrial_blockers),
            "runtime_action_committed_count": 0,
            "hardware_probe_invoked_count": 0,
            "hardware_action_invoked_count": 0,
            "fact_write_allowed_count": 0,
            "no_write_boundary_pass_rate": 1.0,
            "benchmark_score_generated": False,
            "provider_comparison_claimed": False,
        },
        "benchmark_link": {
            "schema_version": "hardware_profile_registry_benchmark_link_report_v1",
            "benchmark_real_values_smoke_available": roots["bench"].is_dir(),
            "current_phase_updates_benchmark_values": False,
            "current_phase_collects_t2": False,
            "ground_truth_available": False,
            "benchmark_score_generated": False,
            "provider_comparison_claimed": False,
        },
        "health_report": {
            "schema_version": "hardware_profile_registry_system_health_report_v1",
            "system_health_governance_available": roots["health"].is_dir(),
            "module_health_report_candidate_generated": False,
            "provider_health_runtime_checked": False,
            "recovery_action_committed": False,
            "capability_mask_consumed": False,
            "no_runtime_health_claim": True,
        },
        "no_write": {
            "schema_version": "hardware_profile_registry_no_write_boundary_report_v1",
            "boundary_ok": True,
            "violations": [],
            "registry_schema_only": True,
            "hardware_probe_invoked": False,
            "runtime_camera_invoked": False,
            "runtime_frame_captured": False,
            "hardware_action_invoked": False,
            "zoom_invoked": False,
            "autofocus_invoked": False,
            "exposure_control_invoked": False,
            "stabilization_invoked": False,
            "detector_invoked": False,
            "ocr_invoked": False,
            "ocrrequest_generated": False,
            "midplatform_fact_written": False,
            "hardware_fact_written": False,
            "scene_delta_written": False,
            "world_model_written": False,
            "benchmark_result_claimed": False,
            "provider_comparison_claimed": False,
            "production_readiness_claimed": False,
        },
        "sim_report": {
            "schema_version": "hardware_profile_registry_simulation_context_report_v1",
            "simulation_profile_id": "developer_full",
            "simulation_context_available": roots["sim"].is_dir(),
            "run_model": False,
            "simulation_context_only": True,
            "runtime_routing_changed": False,
            "ci_default_changed": False,
            "no_hardware_certification_claim": True,
        },
        "non_claims": {
            "schema_version": "hardware_profile_registry_non_claims_report_v1",
            "claims": [
                "no_real_hardware_probe",
                "registry_schema_not_hardware_fact",
                "minimal_unknown_not_device_certification",
                "adapter_placeholder_not_implementation",
                "guardedtrial_later_not_authorization_now",
                "no_camera_no_ocr",
                "no_world_model_write",
                "no_scene_delta",
                "not_production_ready",
            ],
        },
        "followups": {
            "schema_version": "hardware_profile_registry_open_followups_v1",
            "items": FOLLOWUPS,
        },
        "audit": {
            "schema_version": "hardware_profile_registry_audit_report_v1",
            "hardware_profile_capability_registry_v1_executed": True,
            "registry_schema_only": True,
            "hardware_profile_schema_defined": True,
            "camera_capability_registry_schema_defined": True,
            "device_registry_schema_defined": True,
            "sensor_registry_schema_defined": True,
            "capability_status_enum_defined": True,
            "minimal_unknown_profile_generated": True,
            "runtime_adapter_placeholder_defined": True,
            "profile_freshness_policy_defined": True,
            "guardedtrial_precondition_link_defined": True,
            "hardware_probe_invoked": False,
            "runtime_camera_invoked": False,
            "runtime_frame_captured": False,
            "hardware_action_invoked": False,
            "zoom_invoked": False,
            "autofocus_invoked": False,
            "exposure_control_invoked": False,
            "stabilization_invoked": False,
            "detector_invoked": False,
            "ocr_invoked": False,
            "ocrrequest_generated": False,
            "midplatform_fact_written": False,
            "hardware_fact_written": False,
            "scene_delta_candidate_generated": False,
            "world_model_written": False,
            "benchmark_result_claimed": False,
            "provider_comparison_claimed": False,
            "production_readiness_claimed": False,
        },
    }
