# -*- coding: utf-8 -*-
"""Module Boundary Registry Planning item definitions v1."""

from __future__ import annotations

from typing import Any, Dict, Tuple

REGISTRY_ENTRY_REQUIRED_FIELDS: Tuple[str, ...] = (
    "module_id", "module_name", "module_role", "boundary_type", "lifecycle_stage",
    "owned_objects", "consumed_objects", "produced_objects", "not_owned_objects",
    "upstream_module_refs", "downstream_module_refs", "allowed_read_refs",
    "allowed_write_refs", "forbidden_write_refs", "runtime_required_now",
    "implementation_status", "future_dependency_refs",
)

MODULE_BOUNDARY_REGISTRY_DRAFT: Tuple[Dict[str, Any], ...] = (
    {
        "module_id": "task_manager_core_orchestration_skeleton",
        "module_name": "Task Manager Core Orchestration Skeleton",
        "module_role": "orchestration_coordinator",
        "boundary_type": "coordination_layer",
        "lifecycle_stage": "in_progress",
        "owned_objects": ["candidate_flow_state", "module_dispatch_plan"],
        "consumed_objects": ["candidate_lifecycle_events", "protocol_trace_refs", "boundary_lookup_index"],
        "produced_objects": ["orchestration_plan", "candidate_routing_decisions"],
        "not_owned_objects": ["records", "grants", "authorization_requests", "runtime_execution"],
        "upstream_module_refs": ["candidate_lifecycle_manager", "protocol_registry_input_output_traceability", "module_boundary_registry"],
        "downstream_module_refs": ["evidence_record_approval_permission_alignment"],
        "allowed_read_refs": ["candidate_lifecycle_events", "protocol_trace_refs", "boundary_lookup_index"],
        "allowed_write_refs": ["candidate_flow_state", "module_dispatch_plan", "orchestration_plan"],
        "forbidden_write_refs": ["records", "grants", "authorization_requests", "runtime_execution"],
        "runtime_required_now": False,
        "implementation_status": "in_progress",
        "future_dependency_refs": ["runtime_adapter", "whitebox_runtime"],
    },
    {
        "module_id": "module_boundary_registry",
        "module_name": "Module Boundary Registry",
        "module_role": "boundary_registry",
        "boundary_type": "structural_registry",
        "lifecycle_stage": "planned",
        "owned_objects": ["module_boundary_definitions", "ownership_matrix", "boundary_lookup_index"],
        "consumed_objects": ["governance_constraints", "protocol_registry_entries"],
        "produced_objects": ["boundary_lookup_index", "not_owned_declarations"],
        "not_owned_objects": ["candidate_instances", "records", "runtime_bindings", "business_objects"],
        "upstream_module_refs": ["governance_constraints", "protocol_registry_input_output_traceability"],
        "downstream_module_refs": ["candidate_lifecycle_manager", "task_manager_core_orchestration_skeleton", "evidence_record_approval_permission_alignment"],
        "allowed_read_refs": ["governance_constraints", "protocol_registry_entries"],
        "allowed_write_refs": ["module_boundary_definitions", "ownership_matrix", "boundary_lookup_index"],
        "forbidden_write_refs": ["candidate_instances", "records", "runtime_bindings"],
        "runtime_required_now": False,
        "implementation_status": "planned",
        "future_dependency_refs": [],
    },
    {
        "module_id": "candidate_lifecycle_manager",
        "module_name": "Candidate Lifecycle Manager",
        "module_role": "lifecycle_coordinator",
        "boundary_type": "lifecycle_layer",
        "lifecycle_stage": "planned",
        "owned_objects": ["candidate_state_transitions", "lifecycle_stage_registry"],
        "consumed_objects": ["module_boundary_definitions", "protocol_trace_refs"],
        "produced_objects": ["lifecycle_events", "candidate_status_updates"],
        "not_owned_objects": ["records", "grants", "authorization_requests", "runtime_execution"],
        "upstream_module_refs": ["module_boundary_registry", "protocol_registry_input_output_traceability"],
        "downstream_module_refs": ["task_manager_core_orchestration_skeleton", "evidence_record_approval_permission_alignment"],
        "allowed_read_refs": ["module_boundary_definitions", "protocol_trace_refs"],
        "allowed_write_refs": ["candidate_state_transitions", "lifecycle_stage_registry", "lifecycle_events"],
        "forbidden_write_refs": ["records", "grants", "authorization_requests", "runtime_execution"],
        "runtime_required_now": False,
        "implementation_status": "planned",
        "future_dependency_refs": [],
    },
    {
        "module_id": "evidence_record_approval_permission_alignment",
        "module_name": "Evidence Record Approval Permission Alignment",
        "module_role": "alignment_coordinator",
        "boundary_type": "alignment_layer",
        "lifecycle_stage": "planned",
        "owned_objects": ["alignment_rules", "promotion_preconditions"],
        "consumed_objects": ["candidate_lifecycle_events", "orchestration_plan", "boundary_lookup_index"],
        "produced_objects": ["alignment_decisions", "promotion_readiness_flags"],
        "not_owned_objects": ["evidence_records", "approval_records", "grants", "authorization_requests"],
        "upstream_module_refs": ["candidate_lifecycle_manager", "task_manager_core_orchestration_skeleton", "module_boundary_registry"],
        "downstream_module_refs": ["owner_approval_request_closed_module"],
        "allowed_read_refs": ["candidate_lifecycle_events", "orchestration_plan"],
        "allowed_write_refs": ["alignment_rules", "promotion_preconditions", "alignment_decisions"],
        "forbidden_write_refs": ["evidence_records", "approval_records", "grants", "authorization_requests"],
        "runtime_required_now": False,
        "implementation_status": "planned",
        "future_dependency_refs": [],
    },
    {
        "module_id": "protocol_registry_input_output_traceability",
        "module_name": "Protocol Registry Input Output Traceability",
        "module_role": "protocol_traceability",
        "boundary_type": "protocol_layer",
        "lifecycle_stage": "consolidated",
        "owned_objects": ["protocol_registry", "input_output_trace_index", "protocol_metadata"],
        "consumed_objects": ["governance_constraints"],
        "produced_objects": ["protocol_trace_refs", "io_contract_declarations"],
        "not_owned_objects": ["candidate_instances", "records", "runtime_execution", "candidate_lifecycle_runtime"],
        "upstream_module_refs": ["governance_constraints"],
        "downstream_module_refs": ["module_boundary_registry", "candidate_lifecycle_manager", "task_manager_core_orchestration_skeleton"],
        "allowed_read_refs": ["governance_constraints"],
        "allowed_write_refs": ["protocol_registry", "input_output_trace_index", "protocol_metadata"],
        "forbidden_write_refs": ["candidate_instances", "records", "runtime_execution"],
        "runtime_required_now": False,
        "implementation_status": "consolidated",
        "future_dependency_refs": [],
    },
    {
        "module_id": "governance_constraints",
        "module_name": "Governance Constraints",
        "module_role": "governance_cross_cut",
        "boundary_type": "cross_cutting_constraint",
        "lifecycle_stage": "consolidated",
        "owned_objects": ["governance_rules", "development_constraints", "governance_constraint_objects"],
        "consumed_objects": [],
        "produced_objects": ["constraint_refs", "governance_gates"],
        "not_owned_objects": ["candidate_instances", "records", "runtime_execution", "runtime_permission"],
        "upstream_module_refs": [],
        "downstream_module_refs": [
            "protocol_registry_input_output_traceability", "module_boundary_registry",
            "candidate_lifecycle_manager", "task_manager_core_orchestration_skeleton",
            "evidence_record_approval_permission_alignment", "file_size_governance",
        ],
        "allowed_read_refs": [],
        "allowed_write_refs": ["governance_rules", "development_constraints"],
        "forbidden_write_refs": ["runtime_execution", "runtime_permission", "grants", "records"],
        "runtime_required_now": False,
        "implementation_status": "consolidated",
        "future_dependency_refs": [],
    },
    {
        "module_id": "file_size_governance",
        "module_name": "File Size Governance",
        "module_role": "engineering_governance_cross_cut",
        "boundary_type": "cross_cutting_engineering",
        "lifecycle_stage": "consolidated",
        "owned_objects": ["file_size_rules", "module_split_policies", "engineering_governance_objects"],
        "consumed_objects": ["governance_constraints"],
        "produced_objects": ["file_size_governance_reviews"],
        "not_owned_objects": ["candidate_instances", "records", "runtime_execution", "business_objects"],
        "upstream_module_refs": ["governance_constraints"],
        "downstream_module_refs": [],
        "allowed_read_refs": ["governance_constraints"],
        "allowed_write_refs": ["file_size_rules", "module_split_policies", "file_size_governance_reviews"],
        "forbidden_write_refs": ["candidate_instances", "records", "business_objects", "runtime_execution"],
        "runtime_required_now": False,
        "implementation_status": "consolidated",
        "future_dependency_refs": [],
    },
    {
        "module_id": "owner_approval_request_closed_module",
        "module_name": "Owner Approval Request Closed Module",
        "module_role": "downstream_governance_ready_input",
        "boundary_type": "closed_handoff_module",
        "lifecycle_stage": "governance_ready_handoff",
        "owned_objects": ["governance_ready_handoff_package"],
        "consumed_objects": ["alignment_decisions", "functional_slice_dryrun_artifacts"],
        "produced_objects": ["governance_ready_reference"],
        "not_owned_objects": ["new_request_issuance", "record_creation", "grant_creation", "fragmentary_phases"],
        "upstream_module_refs": ["evidence_record_approval_permission_alignment"],
        "downstream_module_refs": [],
        "allowed_read_refs": ["alignment_decisions", "functional_slice_dryrun_artifacts"],
        "allowed_write_refs": ["governance_ready_reference"],
        "forbidden_write_refs": ["new_request_issuance", "record_creation", "grant_creation", "fragmentary_phases"],
        "runtime_required_now": False,
        "implementation_status": "governance_ready_handoff",
        "future_dependency_refs": [],
    },
)

OWNERSHIP_MATRIX: Tuple[Dict[str, Any], ...] = (
    {"object_category": "protocol_objects", "owner_module": "protocol_registry_input_output_traceability", "not_owner": "candidate_lifecycle_manager"},
    {"object_category": "candidate_objects", "owner_module": "candidate_lifecycle_manager", "not_owner": "task_manager_core_orchestration_skeleton"},
    {"object_category": "evidence_objects", "owner_module": "evidence_record_approval_permission_alignment", "not_owner": "candidate_lifecycle_manager", "note": "alignment rules only"},
    {"object_category": "record_objects", "owner_module": None, "not_owner": "all_modules", "note": "no module owns real records"},
    {"object_category": "approval_objects", "owner_module": "evidence_record_approval_permission_alignment", "not_owner": "task_manager_core_orchestration_skeleton", "note": "alignment rules only"},
    {"object_category": "permission_objects", "owner_module": "evidence_record_approval_permission_alignment", "not_owner": "task_manager_core_orchestration_skeleton", "note": "promotion preconditions only"},
    {"object_category": "grant_objects", "owner_module": None, "not_owner": "all_modules", "note": "no module owns grants"},
    {"object_category": "runtime_objects", "owner_module": None, "not_owner": "all_modules", "note": "future runtime debt"},
    {"object_category": "whitebox_objects", "owner_module": None, "not_owner": "all_modules", "note": "future runtime debt"},
    {"object_category": "governance_constraint_objects", "owner_module": "governance_constraints", "not_owner": "protocol_registry_input_output_traceability"},
    {"object_category": "engineering_governance_objects", "owner_module": "file_size_governance", "not_owner": "governance_constraints", "note": "engineering not business"},
)

OWNERSHIP_STATEMENTS: Tuple[str, ...] = (
    "protocol_registry_owns_protocol_metadata_not_candidate_lifecycle_runtime",
    "candidate_lifecycle_manager_owns_candidate_state_transition_plan_not_records_grants_runtime",
    "alignment_owns_boundary_alignment_rules_not_real_record_grant_creation",
    "orchestration_skeleton_coordinates_flows_not_direct_authorization_or_record_creation",
    "owner_approval_request_closed_module_is_downstream_governance_ready_input_not_active_runtime",
    "file_size_governance_owns_engineering_constraints_not_business_objects",
    "governance_constraints_cross_cut_modules_but_do_not_own_runtime_execution",
)

NOT_OWNED_FORBIDDEN_TRANSITIONS: Tuple[Dict[str, Any], ...] = (
    {"module_id": "task_manager_core_orchestration_skeleton", "forbidden": ["create_records", "create_grants", "create_authorization_requests"]},
    {"module_id": "candidate_lifecycle_manager", "forbidden": ["promote_candidate_to_record", "promote_candidate_to_grant", "without_external_authorization"]},
    {"module_id": "evidence_record_approval_permission_alignment", "forbidden": ["create_real_records", "create_real_grants"]},
    {"module_id": "protocol_registry_input_output_traceability", "forbidden": ["execute_runtime"]},
    {"module_id": "owner_approval_request_closed_module", "forbidden": ["reopen_fragmentary_phases", "new_request_issuance"]},
    {"module_id": "file_size_governance", "forbidden": ["mutate_business_state"]},
    {"module_id": "governance_constraints", "forbidden": ["grant_runtime_permission"]},
    {"module_id": "module_boundary_registry", "forbidden": ["create_candidate_instances", "execute_runtime_registry"]},
)

BOUNDARY_CONFLICT_DETECTION_CHECKS: Tuple[Dict[str, str], ...] = (
    {"check_id": "duplicated_ownership", "description": "Two modules claim same object category"},
    {"check_id": "missing_owner", "description": "Object category has no declared owner when required"},
    {"check_id": "forbidden_write", "description": "Module writes to forbidden_write_refs object"},
    {"check_id": "candidate_promoted_to_record", "description": "Candidate promoted to real record without authorization"},
    {"check_id": "permission_promoted_to_grant", "description": "Permission candidate promoted to grant without authorization"},
    {"check_id": "protocol_metadata_as_runtime", "description": "Protocol metadata treated as runtime execution"},
    {"check_id": "closed_module_reopened", "description": "Owner approval request closed module reopened"},
    {"check_id": "future_runtime_debt_as_implementation", "description": "Future runtime debt treated as current implementation"},
)

BOUNDARY_DEPENDENCY_NODES: Tuple[str, ...] = (
    "governance_constraints", "file_size_governance", "protocol_registry_input_output_traceability",
    "module_boundary_registry", "candidate_lifecycle_manager", "evidence_record_approval_permission_alignment",
    "task_manager_core_orchestration_skeleton", "owner_approval_request_closed_module",
)

BOUNDARY_DEPENDENCY_EDGES: Tuple[Dict[str, str], ...] = (
    {"from": "governance_constraints", "to": "protocol_registry_input_output_traceability", "type": "cross_cut"},
    {"from": "governance_constraints", "to": "module_boundary_registry", "type": "cross_cut"},
    {"from": "governance_constraints", "to": "candidate_lifecycle_manager", "type": "cross_cut"},
    {"from": "governance_constraints", "to": "task_manager_core_orchestration_skeleton", "type": "cross_cut"},
    {"from": "governance_constraints", "to": "evidence_record_approval_permission_alignment", "type": "cross_cut"},
    {"from": "governance_constraints", "to": "file_size_governance", "type": "cross_cut"},
    {"from": "file_size_governance", "to": "protocol_registry_input_output_traceability", "type": "engineering_cross_cut"},
    {"from": "protocol_registry_input_output_traceability", "to": "module_boundary_registry", "type": "upstream"},
    {"from": "module_boundary_registry", "to": "candidate_lifecycle_manager", "type": "upstream"},
    {"from": "module_boundary_registry", "to": "evidence_record_approval_permission_alignment", "type": "upstream"},
    {"from": "candidate_lifecycle_manager", "to": "task_manager_core_orchestration_skeleton", "type": "upstream"},
    {"from": "task_manager_core_orchestration_skeleton", "to": "evidence_record_approval_permission_alignment", "type": "upstream"},
    {"from": "evidence_record_approval_permission_alignment", "to": "owner_approval_request_closed_module", "type": "downstream_handoff"},
    {"from": "runtime_adapter", "to": "task_manager_core_orchestration_skeleton", "type": "future_dependency"},
    {"from": "whitebox_runtime", "to": "runtime_adapter", "type": "future_dependency"},
    {"from": "real_execution_preauth", "to": "whitebox_runtime", "type": "future_dependency"},
)

SELECTED_NEXT_ROUTE = "Candidate Lifecycle Unification Planning"
NEXT_ROUTE_A = "Phase-Midplatform-Candidate-Lifecycle-Unification-Planning-v1-001"
NEXT_ROUTE_B = "Phase-Midplatform-Evidence-Record-Approval-Permission-Alignment-Planning-v1-001"
NEXT_ROUTE_C = "Phase-Midplatform-Task-Manager-Core-Orchestration-Skeleton-Consolidation-v1-001"
NEXT_ROUTE_D = "Phase-Midplatform-Module-Boundary-Registry-DryRun-v1-001"
NEXT_ROUTE_E = "Phase-Midplatform-Governance-Debt-Consolidation-v1-001"

FORBIDDEN_OWNERSHIP_PAIRS: Tuple[Tuple[str, str], ...] = (
    ("task_manager_core_orchestration_skeleton", "records"),
    ("task_manager_core_orchestration_skeleton", "grants"),
    ("task_manager_core_orchestration_skeleton", "authorization_requests"),
    ("task_manager_core_orchestration_skeleton", "runtime_execution"),
    ("candidate_lifecycle_manager", "records"),
    ("candidate_lifecycle_manager", "grants"),
    ("candidate_lifecycle_manager", "runtime_execution"),
    ("evidence_record_approval_permission_alignment", "evidence_records"),
    ("evidence_record_approval_permission_alignment", "grants"),
    ("protocol_registry_input_output_traceability", "runtime_execution"),
    ("file_size_governance", "business_objects"),
    ("governance_constraints", "runtime_permission"),
)
