# -*- coding: utf-8 -*-
"""OCR Evidence Pack spatiotemporal + semantic contract (schema only).

Phase-OCR-Evidence-Pack-SpatioTemporal-Semantic-Contract-001
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Tuple

PHASE_ID = "OCR-Evidence-Pack-SpatioTemporal-Semantic-Contract-001"

OCR_TEXT_EVIDENCE_PACK_TEMPLATE: Dict[str, Any] = {
    "evidence_id": "ocr_ev_<uuid>",
    "evidence_type": "OCRTextEvidence",
    "schema_version": "ocr_text_evidence_pack_v0",
    "source": {
        "source_type": "video_frame | image | roi | live_camera",
        "video_id": None,
        "frame_id": None,
        "image_id": None,
        "roi_id": None,
        "stream_id": None,
        "provider_request_id": None,
        "source_chain": [],
    },
    "raw_ocr": {
        "raw_ocr_text": "",
        "text_items": [],
        "language_candidates": [],
        "provider": "rapidocr_candidate | paddleocr_candidate | other",
        "provider_version": None,
        "provider_confidence": None,
        "empty_text": False,
        "raw_output_ref": None,
        "raw_ocr_text_preserved": True,
    },
    "image_coordinates": {
        "coordinate_system": "pixel",
        "image_width": None,
        "image_height": None,
        "bbox_xyxy": [None, None, None, None],
        "bbox_xywh": [None, None, None, None],
        "polygon": [],
        "roi_bbox_xyxy": [None, None, None, None],
        "text_line_boxes": [],
        "reading_order_index": None,
        "coordinate_confidence": None,
    },
    "temporal_coordinates": {
        "timestamp_ms": None,
        "video_time_sec": None,
        "frame_index": None,
        "capture_time_utc": None,
        "observation_time_monotonic_ms": None,
        "ttl_observed_at": None,
        "validity_period_candidate": None,
    },
    "spatial_coordinates": {
        "coordinate_source": "gps | visual_slam | map_anchor | indoor_anchor | unknown",
        "gps_lat": None,
        "gps_lng": None,
        "gps_accuracy_m": None,
        "altitude_m": None,
        "heading_deg": None,
        "device_pose": None,
        "camera_pose": None,
        "relative_position": {
            "distance_m": None,
            "bearing_deg": None,
            "height_relative_m": None,
        },
        "map_anchor_id": None,
        "place_candidate_id": None,
        "spatial_confidence": None,
    },
    "readability_quality": {
        "readability_grade": "A | B | C | D | E | unknown",
        "text_frontality_score": None,
        "text_size_level": None,
        "occlusion_level": None,
        "motion_blur_level": None,
        "compression_artifact_level": None,
        "angle_skew_level": None,
        "lighting_quality": None,
        "contrast_score": None,
        "partial_text_visible": None,
        "multi_frame_recoverable": None,
        "logo_or_visual_symbol_likelihood": None,
        "public_facility_semantic_likelihood": None,
    },
    "evidence_status": {
        "fact_status": "not_fact",
        "write_allowed": False,
        "requires_review": True,
        "confidence": None,
        "uncertainty_reasons": [],
        "risk_flags": [],
        "boundary_flags": [],
    },
}

SEMANTIC_CANDIDATE_TEMPLATE: Dict[str, Any] = {
    "semantic_candidate_id": "ocr_sem_<uuid>",
    "source_ocr_evidence_id": "...",
    "schema_version": "ocr_semantic_candidate_v0",
    "semantic_scope": "midplatform_interpretation_candidate",
    "raw_ocr_text": "",
    "normalized_text_candidate": None,
    "correction_candidate": None,
    "completion_candidate": None,
    "meaning_candidate": {
        "semantic_type": "store_sign | bank_sign | doorplate | public_facility | warning_sign | poster_promo | traffic_sign | unknown",
        "entity_type_candidate": "bank | store | restroom | exit | no_smoking | brand | address | promo | unknown",
        "entity_name_candidate": None,
        "place_function_candidate": None,
        "actionability_candidate": None,
        "human_readable_meaning_candidate": None,
    },
    "interpretation_basis": {
        "ocr_text_ref": None,
        "visual_context_ref": None,
        "public_facility_registry_ref": None,
        "visual_symbol_registry_ref": None,
        "map_context_ref": None,
        "memory_context_ref": None,
        "multi_frame_context_ref": None,
    },
    "governance": {
        "semantic_candidate_not_fact": True,
        "raw_text_overwritten": False,
        "completion_committed": False,
        "requires_midplatform_arbitration": True,
        "requires_source_validation": True,
        "requires_review": True,
        "fact_status": "not_fact",
        "write_allowed": False,
    },
}

WORLD_MODEL_ATTACH_TEMPLATE: Dict[str, Any] = {
    "world_model_attach_candidate_id": "wm_attach_<uuid>",
    "source_ocr_evidence_id": "...",
    "source_semantic_candidate_id": "...",
    "schema_version": "ocr_world_model_attach_candidate_v0",
    "attach_scope": "candidate_only",
    "target_world_model_layer": "place | sign | facility | commercial_activity | warning | temporal_event | unknown",
    "target_anchor": {
        "spatial_anchor_candidate": None,
        "map_anchor_candidate": None,
        "place_candidate": None,
        "building_candidate": None,
        "poi_candidate": None,
    },
    "candidate_content": {
        "raw_text": "",
        "semantic_meaning": None,
        "entity_candidate": None,
        "function_candidate": None,
        "temporal_validity_candidate": None,
        "commercial_claim_candidate": None,
        "public_facility_candidate": None,
    },
    "write_preconditions": {
        "source_validation_required": True,
        "conflict_detection_required": True,
        "ttl_required": False,
        "review_required": True,
        "multi_observation_required": False,
        "user_visible_uncertainty_required": True,
        "world_model_write_gate_required": True,
    },
    "status": {
        "attach_candidate_not_fact": True,
        "world_model_write_allowed": False,
        "scene_delta_candidate_allowed": False,
        "fact_status": "not_fact",
        "write_allowed": False,
    },
}

COORDINATE_REQUIREMENTS: Tuple[Dict[str, Any], ...] = (
    {
        "coordinate_type": "image_pixel_bbox",
        "required": True,
        "nullable": True,
        "source_provider": "ocr_provider_or_roi_proposal",
        "failure_behavior": "reject_submission_if_missing_when_grade_A",
        "downstream_usage": ["semantic_candidate", "world_model_anchor_candidate"],
    },
    {
        "coordinate_type": "image_polygon",
        "required": False,
        "nullable": True,
        "source_provider": "ocr_provider",
        "failure_behavior": "optional_enrichment",
        "downstream_usage": ["readability_scoring"],
    },
    {
        "coordinate_type": "roi_bbox",
        "required": True,
        "nullable": True,
        "source_provider": "vision_roi_proposal",
        "failure_behavior": "use_full_frame_only_if_explicitly_allowed",
        "downstream_usage": ["ocr_submission", "world_model_anchor_candidate"],
    },
    {
        "coordinate_type": "frame_timestamp",
        "required": True,
        "nullable": True,
        "source_provider": "video_frame_ingest",
        "failure_behavior": "reject_if_video_source_and_missing",
        "downstream_usage": ["ttl_policy", "multiframe_recovery"],
    },
    {
        "coordinate_type": "video_time",
        "required": True,
        "nullable": True,
        "source_provider": "video_frame_ingest",
        "failure_behavior": "derive_from_frame_index_if_possible",
        "downstream_usage": ["temporal_validity_candidate"],
    },
    {
        "coordinate_type": "capture_time",
        "required": False,
        "nullable": True,
        "source_provider": "device_metadata",
        "failure_behavior": "null_not_fabricated",
        "downstream_usage": ["audit"],
    },
    {
        "coordinate_type": "gps_coordinate",
        "required": True,
        "nullable": True,
        "source_provider": "gps_or_unknown",
        "failure_behavior": "null_not_fabricated",
        "downstream_usage": ["world_model_anchor_candidate", "place_candidate"],
    },
    {
        "coordinate_type": "device_pose",
        "required": False,
        "nullable": True,
        "source_provider": "slam_or_unknown",
        "failure_behavior": "null_not_fabricated",
        "downstream_usage": ["spatial_anchor_candidate"],
    },
    {
        "coordinate_type": "camera_pose",
        "required": False,
        "nullable": True,
        "source_provider": "slam_or_unknown",
        "failure_behavior": "null_not_fabricated",
        "downstream_usage": ["spatial_anchor_candidate"],
    },
    {
        "coordinate_type": "relative_position",
        "required": False,
        "nullable": True,
        "source_provider": "visual_geometry",
        "failure_behavior": "null_not_fabricated",
        "downstream_usage": ["navigation_hint_candidate_only"],
    },
    {
        "coordinate_type": "map_anchor",
        "required": False,
        "nullable": True,
        "source_provider": "map_service",
        "failure_behavior": "null_not_fabricated",
        "downstream_usage": ["world_model_attach_candidate"],
    },
    {
        "coordinate_type": "place_candidate",
        "required": False,
        "nullable": True,
        "source_provider": "map_or_semantic_inference",
        "failure_behavior": "candidate_only_not_fact",
        "downstream_usage": ["world_model_attach_candidate"],
    },
)

SEMANTIC_MEANING_TYPES: Tuple[Dict[str, Any], ...] = (
    {
        "semantic_type": "bank_sign",
        "description": "Bank branch or ATM signage",
        "example_text": "中国建设银行 / Construction Bank",
        "allowed_world_model_layer": ["place", "sign"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "store_sign",
        "description": "Retail or service storefront sign",
        "example_text": "美式眼镜",
        "allowed_world_model_layer": ["place", "sign", "commercial_activity"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "brand_sign",
        "description": "Logo-dominant brand signage",
        "example_text": "GAP",
        "allowed_world_model_layer": ["sign"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": True,
        "fact_write_default": False,
    },
    {
        "semantic_type": "doorplate",
        "description": "Doorplate or unit label",
        "example_text": "3F-301",
        "allowed_world_model_layer": ["place", "sign"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "road_sign",
        "description": "Road or traffic related text sign",
        "example_text": "前方施工",
        "allowed_world_model_layer": ["warning", "sign"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "public_facility_sign",
        "description": "Public facility directional or functional sign",
        "example_text": "洗手间",
        "allowed_world_model_layer": ["facility"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": True,
        "fact_write_default": False,
    },
    {
        "semantic_type": "no_smoking_sign",
        "description": "No smoking rule signage",
        "example_text": "禁烟 NO SMOKING",
        "allowed_world_model_layer": ["warning", "public_rule"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "exit_sign",
        "description": "Exit signage",
        "example_text": "EXIT / 安全出口",
        "allowed_world_model_layer": ["facility", "warning"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": True,
        "fact_write_default": False,
    },
    {
        "semantic_type": "restroom_sign",
        "description": "Restroom signage",
        "example_text": "卫生间",
        "allowed_world_model_layer": ["facility"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": True,
        "fact_write_default": False,
    },
    {
        "semantic_type": "elevator_sign",
        "description": "Elevator signage",
        "example_text": "电梯",
        "allowed_world_model_layer": ["facility"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": True,
        "fact_write_default": False,
    },
    {
        "semantic_type": "poster_promo_text",
        "description": "Poster or notice promotional text",
        "example_text": "海派夜韵 购夜食夜游",
        "allowed_world_model_layer": ["commercial_activity", "sign"],
        "requires_ttl": True,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "temporal_notice_text",
        "description": "Time-bound notice",
        "example_text": "营业时间 10:00-22:00",
        "allowed_world_model_layer": ["temporal_event", "commercial_activity"],
        "requires_ttl": True,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "price_discount_text",
        "description": "Price or discount promotional text",
        "example_text": "50% OFF",
        "allowed_world_model_layer": ["commercial_activity"],
        "requires_ttl": True,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "warning_notice",
        "description": "Warning or caution notice",
        "example_text": "小心地滑",
        "allowed_world_model_layer": ["warning"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
    {
        "semantic_type": "unknown_text",
        "description": "Unclassified OCR text",
        "example_text": "",
        "allowed_world_model_layer": ["unknown"],
        "requires_ttl": False,
        "requires_source_validation": True,
        "requires_visual_symbol_support": False,
        "fact_write_default": False,
    },
)

ENHANCEMENT_OPS: Tuple[Tuple[str, bool, str, str, bool], ...] = (
    ("normalize_text_candidate", True, "normalized_text_candidate", "dictionary", True),
    ("typo_correction_candidate", True, "correction_candidate", "gt_or_rules", True),
    ("partial_completion_candidate", True, "completion_candidate", "multiframe_or_gt", True),
    ("common_entity_match_candidate", True, "entity_name_candidate", "entity_prior", True),
    ("semantic_meaning_candidate", True, "meaning_candidate", "midplatform_classifier", True),
    ("visual_context_hint_candidate", True, "interpretation_basis.visual_context_ref", "visual_symbol", True),
    ("multi_frame_merge_candidate", True, "completion_candidate", "multiframe_alignment", True),
    ("public_facility_correction_candidate", True, "correction_candidate", "facility_registry", True),
    ("overwrite_raw_ocr_text", False, "forbidden", "n/a", True),
    ("commit_completion_without_review", False, "forbidden", "n/a", True),
    ("write_enhanced_text_as_fact", False, "forbidden", "n/a", True),
    ("use_enhancement_for_navigation_decision", False, "forbidden", "n/a", True),
    ("hide_uncertainty_from_user", False, "forbidden", "n/a", True),
    ("delete_raw_evidence", False, "forbidden", "n/a", True),
)

ARBITRATION_STEPS: Tuple[Dict[str, Any], ...] = (
    {
        "step_id": "raw_evidence_read",
        "input": ["OCRTextEvidence"],
        "output": ["raw_ocr_preserved"],
        "allowed": True,
        "forbidden": ["overwrite_raw_ocr_text"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "enhancement_candidate_generation",
        "input": ["OCRTextEvidence", "readability_quality"],
        "output": ["normalize/correction/completion candidates"],
        "allowed": True,
        "forbidden": ["commit_completion"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "visual_context_check",
        "input": ["visual_symbol_refs", "logo_likelihood"],
        "output": ["visual_context_hint_candidate"],
        "allowed": True,
        "forbidden": ["brand_fact_without_registry"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "semantic_type_classification",
        "input": ["raw_ocr", "meaning_type_registry"],
        "output": ["OCRSemanticCandidate.meaning_candidate"],
        "allowed": True,
        "forbidden": ["write_as_fact"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "world_model_attach_candidate_generation",
        "input": ["OCRSemanticCandidate", "spatial_coordinates"],
        "output": ["WorldModelAttachCandidate"],
        "allowed": True,
        "forbidden": ["write_world_model"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "conflict_check",
        "input": ["attach_candidates", "existing_wm_refs"],
        "output": ["conflict_flags"],
        "allowed": True,
        "forbidden": ["auto_resolve_as_fact"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "ttl_check",
        "input": ["semantic_type", "temporal_coordinates"],
        "output": ["ttl_required_flag"],
        "allowed": True,
        "forbidden": ["skip_ttl_for_commercial"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "source_validation",
        "input": ["source_chain", "gt_refs"],
        "output": ["validation_status"],
        "allowed": True,
        "forbidden": ["fabricate_source"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "review_gate",
        "input": ["all_candidates"],
        "output": ["review_status"],
        "allowed": True,
        "forbidden": ["auto_approve"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
    {
        "step_id": "write_gate",
        "input": ["review_status", "attach_preconditions"],
        "output": ["world_model_write_decision"],
        "allowed": True,
        "forbidden": ["write_without_gate"],
        "fact_status_after_step": "not_fact",
        "write_allowed_after_step": False,
    },
)

WM_ATTACH_GATES: Tuple[Dict[str, Any], ...] = (
    ("spatial_anchor_required", True, True, False, "no_spatial_anchor_in_contract_phase"),
    ("source_validation_required", True, True, False, "validation_not_run_in_contract_phase"),
    ("semantic_confidence_required", True, True, False, "confidence_not_computed"),
    ("conflict_check_required", True, True, False, "conflict_engine_not_run"),
    ("ttl_policy_required_if_temporal_or_commercial", True, True, False, "ttl_policy_linked_not_executed"),
    ("review_required_if_uncertain", True, True, False, "review_queue_not_run"),
    ("multi_observation_required_if_low_confidence", True, False, False, "multiframe_not_run"),
    ("user_visible_uncertainty_required", True, True, False, "ui_policy_not_run"),
)


def _read_json(p: Path) -> Any:
    if not p.is_file():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def run_ocr_evidence_pack_spatiotemporal_semantic_contract_v0(
    *,
    benchmark_real_values_smoke_root: str,
    system_health_governance_root: str,
    simulation_lab_harness_root: str,
    output_root: str,
) -> Tuple[
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    Dict[str, Any],
    List[str],
]:
    errs: List[str] = []
    bench = Path(benchmark_real_values_smoke_root).resolve()
    health = Path(system_health_governance_root).resolve()
    sim = Path(simulation_lab_harness_root).resolve()
    out = Path(output_root).resolve()

    summary = {
        "schema_version": "ocr_evidence_pack_contract_summary_v0",
        "phase": PHASE_ID,
        "contract_scope": "schema_and_governance_only",
        "ocr_evidence_pack_defined": True,
        "image_coordinate_required": True,
        "spatiotemporal_coordinate_required": True,
        "source_chain_required": True,
        "readability_quality_required": True,
        "semantic_candidate_required": True,
        "world_model_attach_candidate_required": True,
        "raw_ocr_text_preserved_required": True,
        "semantic_candidate_not_fact": True,
        "world_model_attach_candidate_not_fact": True,
        "runtime_execution": False,
        "ocr_invoked": False,
        "vision_provider_invoked": False,
        "midplatform_fact_written": False,
        "scene_delta_written": False,
        "world_model_written": False,
        "navigation_decision_invoked": False,
        "runtime_routing_changed": False,
        "fact_status": "not_fact",
        "write_allowed": False,
        "phase_verdict_hint": "GO",
        "output_root": str(out),
    }

    ocr_pack_schema = {
        "schema_version": "ocr_text_evidence_pack_schema_v0",
        "description": "Unified OCRTextEvidence pack with image/temporal/spatial coordinates",
        "template": OCR_TEXT_EVIDENCE_PACK_TEMPLATE,
        "required_top_level_keys": list(OCR_TEXT_EVIDENCE_PACK_TEMPLATE.keys()),
        "defaults": {
            "raw_ocr.raw_ocr_text_preserved": True,
            "evidence_status.fact_status": "not_fact",
            "evidence_status.write_allowed": False,
        },
        "null_policy": "missing_fields_must_be_explicit_null_not_fabricated",
    }

    semantic_schema = {
        "schema_version": "ocr_semantic_candidate_schema_v0",
        "description": "Midplatform semantic interpretation candidate; not fact",
        "template": SEMANTIC_CANDIDATE_TEMPLATE,
        "chain_position": "OCRTextEvidence -> OCRSemanticCandidate",
        "policies": {
            "meaning_candidate_generated_by_midplatform": True,
            "semantic_candidate_must_not_overwrite_ocr_raw": True,
            "completion_must_not_pretend_as_seen_text": True,
            "semantic_candidate_not_fact": True,
        },
    }

    wm_attach_schema = {
        "schema_version": "ocr_world_model_attach_candidate_schema_v0",
        "description": "WorldModel attach candidate only; not WorldModel fact",
        "template": WORLD_MODEL_ATTACH_TEMPLATE,
        "chain_position": "OCRSemanticCandidate -> WorldModelAttachCandidate -> Gate",
        "policies": {
            "attach_candidate_not_fact": True,
            "world_model_write_allowed_default": False,
            "scene_delta_candidate_allowed_default": False,
        },
    }

    coord_matrix = {
        "schema_version": "ocr_evidence_coordinate_requirements_matrix_v0",
        "row_count": len(COORDINATE_REQUIREMENTS),
        "rows": list(COORDINATE_REQUIREMENTS),
        "policies": {
            "image_pixel_bbox_required": True,
            "timestamp_required": True,
            "spatial_coordinate_required": True,
            "spatial_coordinate_nullable": True,
            "do_not_fabricate_missing_spatial": True,
        },
    }

    meaning_registry = {
        "schema_version": "ocr_semantic_meaning_type_registry_v0",
        "type_count": len(SEMANTIC_MEANING_TYPES),
        "types": list(SEMANTIC_MEANING_TYPES),
    }

    enhancement_matrix = {
        "schema_version": "ocr_enhancement_operation_matrix_v0",
        "operations": [
            {
                "operation": op,
                "allowed": allowed,
                "output_field": out_field,
                "required_input": req_in,
                "required_review": review,
                "fact_status": "not_fact",
                "write_allowed": False,
            }
            for op, allowed, out_field, req_in, review in ENHANCEMENT_OPS
        ],
    }

    examples = {
        "schema_version": "ocr_evidence_pack_examples_v0",
        "example_count": 4,
        "chain": "OCRTextEvidence -> OCRSemanticCandidate -> WorldModelAttachCandidate -> Gate",
        "examples": [
            {
                "example_id": "construction_bank_occluded",
                "raw_ocr_text": "建设银行 / Construction Bank",
                "missing_text_candidate": "中国",
                "semantic_type_candidate": "bank_sign",
                "entity_name_candidate": "中国建设银行",
                "raw_ocr_text_preserved": True,
                "completion_committed": False,
                "readability_grade": "B",
                "fact_status": "not_fact",
                "world_model_attach_candidate": "bank_sign_place_candidate",
            },
            {
                "example_id": "gap_logo_sign",
                "raw_ocr_text": None,
                "raw_ocr_text_note": "null_or_unstable",
                "semantic_type_candidate": "brand_sign",
                "route_to_visual_symbol_evidence": True,
                "brand_identity_confirmed": False,
                "fact_status": "not_fact",
            },
            {
                "example_id": "american_style_glasses_sign",
                "raw_ocr_text": "partial_or_unstable",
                "semantic_type_candidate": "store_sign",
                "readability_grade": "C",
                "requires_resample_or_multiframe": True,
                "fact_status": "not_fact",
            },
            {
                "example_id": "no_smoking_sign",
                "raw_ocr_text": "禁烟 NO SMOKING",
                "semantic_type_candidate": "no_smoking_sign",
                "public_rule_candidate": True,
                "world_model_attach_candidate": "warning_or_public_rule_candidate",
                "fact_status": "not_fact",
            },
        ],
    }

    arbitration = {
        "schema_version": "ocr_semantic_midplatform_arbitration_policy_v0",
        "step_count": len(ARBITRATION_STEPS),
        "steps": list(ARBITRATION_STEPS),
        "write_allowed_until_write_gate": False,
    }

    wm_gates = {
        "schema_version": "ocr_world_model_attach_gate_policy_v0",
        "gates": [
            {
                "gate_id": gid,
                "required_for_world_model_write": req_wm,
                "required_for_scene_delta_candidate": req_sd,
                "satisfied_in_this_phase": sat,
                "missing_reason": reason,
            }
            for gid, req_wm, req_sd, sat, reason in WM_ATTACH_GATES
        ],
    }

    metrics = {
        "schema_version": "ocr_evidence_pack_metrics_binding_plan_v0",
        "future_metrics": [
            "ocr_evidence_pack_count",
            "evidence_with_image_bbox_count",
            "evidence_with_timestamp_count",
            "evidence_with_spatial_anchor_count",
            "semantic_candidate_count",
            "world_model_attach_candidate_count",
            "raw_text_preservation_rate",
            "enhancement_candidate_count",
            "completion_candidate_count",
            "attach_candidate_not_fact_rate",
            "world_model_write_block_rate",
            "no_write_boundary_pass_rate",
        ],
        "current_phase_collects_metrics": False,
        "current_phase_updates_benchmark": False,
        "t2_metrics_require_ground_truth": True,
    }

    benchmark_link = {
        "schema_version": "ocr_evidence_pack_benchmark_link_report_v0",
        "benchmark_smoke_root": str(bench),
        "benchmark_real_values_smoke_available": bench.is_dir(),
        "current_phase_updates_benchmark_values": False,
        "current_phase_collects_t1": False,
        "current_phase_collects_t2": False,
        "ground_truth_required_for_t2": True,
        "benchmark_score_generated": False,
        "provider_comparison_claimed": False,
    }

    health_link = {
        "schema_version": "ocr_evidence_pack_system_health_link_report_v0",
        "system_health_governance_root": str(health),
        "system_health_governance_available": health.is_dir(),
        "module_health_report_generated": False,
        "provider_health_runtime_checked": False,
        "recovery_action_committed": False,
        "capability_mask_consumed": False,
        "no_runtime_health_claim": True,
    }

    boundary = {
        "schema_version": "ocr_evidence_pack_no_write_boundary_report_v0",
        "boundary_ok": True,
        "violations": [],
        "contract_only": True,
        "runtime_execution": False,
        "video_loaded": False,
        "frame_sampled": False,
        "ocr_invoked": False,
        "rapidocr_invoked": False,
        "paddleocr_invoked": False,
        "vision_provider_invoked": False,
        "semantic_model_invoked": False,
        "world_model_attach_executed": False,
        "scene_delta_candidate_generated": False,
        "midplatform_fact_written": False,
        "scene_delta_written": False,
        "world_model_written": False,
        "navigation_decision_invoked": False,
        "auto_approve_invoked": False,
        "approval_granted": False,
        "runtime_routing_changed": False,
    }

    sim_sm = _read_json(sim / "simulation_summary.json") or {}
    sim_report = {
        "schema_version": "ocr_evidence_pack_simulation_context_report_v0",
        "simulation_profile_id": sim_sm.get("simulation_profile_id") or "developer_full",
        "simulation_output_root": sim_sm.get("simulation_output_root") or str(sim),
        "run_model": sim_sm.get("run_model", False),
        "simulation_context_only": True,
        "runtime_routing_changed": False,
        "ci_default_changed": False,
        "no_hardware_certification_claim": True,
    }

    non_claims = {
        "schema_version": "ocr_evidence_pack_non_claims_report_v0",
        "no_ocr_execution": True,
        "no_semantic_model_execution": True,
        "no_real_semantic_candidate_generation": True,
        "no_real_world_model_attach_execution": True,
        "no_world_model_write": True,
        "not_ocr_accuracy": True,
        "not_benchmark": True,
        "not_provider_superiority": True,
        "not_scene_delta_readiness": True,
        "not_navigation": True,
        "not_production_ready": True,
    }

    followups = {
        "schema_version": "ocr_evidence_pack_open_followups_v0",
        "items": [
            "OCR Evidence Pack adapter update",
            "OCR Semantic Candidate generator dry-run",
            "WorldModel Attach Candidate dry-run",
            "Spatial anchor provider integration",
            "Time/TTL policy integration",
            "VisualSymbolRegistry integration",
            "PublicFacility semantic-first integration",
            "Multi-frame OCR enhancement",
            "Ground truth annotation schema",
            "Benchmark T2 collector",
        ],
        "item_count": 10,
    }

    audit = {
        "schema_version": "ocr_evidence_pack_audit_v0",
        "ocr_evidence_pack_contract_executed": True,
        "contract_only": True,
        "runtime_execution": False,
        "ocr_invoked": False,
        "rapidocr_invoked": False,
        "paddleocr_invoked": False,
        "vision_provider_invoked": False,
        "semantic_model_invoked": False,
        "world_model_attach_executed": False,
        "scene_delta_candidate_generated": False,
        "midplatform_fact_written": False,
        "scene_delta_written": False,
        "world_model_written": False,
        "navigation_decision_invoked": False,
        "auto_approve_invoked": False,
        "approval_granted": False,
        "runtime_routing_changed": False,
        "benchmark_result_claimed": False,
        "provider_comparison_claimed": False,
        "model_selection_claimed": False,
        "production_readiness_claimed": False,
    }

    return (
        summary,
        ocr_pack_schema,
        semantic_schema,
        wm_attach_schema,
        coord_matrix,
        meaning_registry,
        enhancement_matrix,
        examples,
        arbitration,
        wm_gates,
        metrics,
        benchmark_link,
        health_link,
        boundary,
        sim_report,
        non_claims,
        followups,
        audit,
        errs,
    )
