# -*- coding: utf-8 -*-
"""Work item definitions for Broader Midplatform Remaining Work Roadmap v1."""

from __future__ import annotations

from typing import Any, Dict, Tuple

WORK_MATRIX_REQUIRED_FIELDS: Tuple[str, ...] = (
    "work_id",
    "work_name",
    "category",
    "current_status",
    "priority",
    "required_before_module_completion",
    "required_before_integration_test",
    "required_before_runtime",
    "can_defer",
    "blocker_now",
    "dependency_refs",
    "recommended_phase",
)

REMAINING_WORK_ITEMS: Tuple[Dict[str, Any], ...] = (
    {
        "work_id": "broader_module_completion",
        "work_name": "Broader Module Completion",
        "category": "construction",
        "current_status": "planned",
        "priority": "P2",
        "required_before_module_completion": True,
        "required_before_integration_test": True,
        "required_before_runtime": True,
        "can_defer": False,
        "blocker_now": False,
        "dependency_refs": ["foundation_consolidation_package"],
        "recommended_phase": "Phase-Midplatform-Task-Manager-Module-Integration-Planning-v1-001",
    },
    {
        "work_id": "module_integration_planning",
        "work_name": "Module Integration Planning",
        "category": "planning",
        "current_status": "next_candidate",
        "priority": "P2",
        "required_before_module_completion": True,
        "required_before_integration_test": True,
        "required_before_runtime": True,
        "can_defer": False,
        "blocker_now": False,
        "dependency_refs": ["remaining_work_roadmap"],
        "recommended_phase": "Phase-Midplatform-Task-Manager-Module-Integration-Planning-v1-001",
    },
    {
        "work_id": "midplatform_module_boundary_registry",
        "work_name": "Midplatform Module Boundary Registry",
        "category": "planning",
        "current_status": "planned",
        "priority": "P2",
        "required_before_module_completion": True,
        "required_before_integration_test": True,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["module_integration_planning"],
        "recommended_phase": "Phase-Midplatform-Module-Boundary-Registry-Planning-v1-001",
    },
    {
        "work_id": "candidate_lifecycle_unification",
        "work_name": "Candidate Lifecycle Unification",
        "category": "planning",
        "current_status": "planned",
        "priority": "P2",
        "required_before_module_completion": True,
        "required_before_integration_test": True,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["module_integration_planning"],
        "recommended_phase": "Phase-Midplatform-Candidate-Lifecycle-Unification-Planning-v1-001",
    },
    {
        "work_id": "evidence_record_approval_permission_alignment",
        "work_name": "Evidence Record Approval Permission Alignment",
        "category": "planning",
        "current_status": "planned",
        "priority": "P2",
        "required_before_module_completion": True,
        "required_before_integration_test": True,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["module_integration_planning", "owner_approval_request_closed_module"],
        "recommended_phase": "Phase-Midplatform-Task-Manager-Module-Integration-Planning-v1-001",
    },
    {
        "work_id": "governance_debt_consolidation",
        "work_name": "Governance Debt Consolidation",
        "category": "optional_quality",
        "current_status": "planned",
        "priority": "P2",
        "required_before_module_completion": False,
        "required_before_integration_test": False,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["governance_constraints"],
        "recommended_phase": "Phase-Midplatform-Governance-Debt-Consolidation-v1-001",
    },
    {
        "work_id": "integration_test_planning",
        "work_name": "Integration Test Planning",
        "category": "deferred_test",
        "current_status": "deferred",
        "priority": "P3",
        "required_before_module_completion": False,
        "required_before_integration_test": True,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["module_integration_planning"],
        "recommended_phase": "Phase-Midplatform-Task-Manager-Integration-Test-Planning-v1-001",
    },
    {
        "work_id": "future_runtime_debt_registry",
        "work_name": "Future Runtime Debt Registry",
        "category": "future_runtime_debt",
        "current_status": "deferred",
        "priority": "P4",
        "required_before_module_completion": False,
        "required_before_integration_test": False,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": [],
        "recommended_phase": "Phase-Midplatform-Future-Runtime-Debt-Registry-v1-001",
    },
    {
        "work_id": "runtime_adapter_implementation",
        "work_name": "Runtime Adapter Implementation",
        "category": "future_runtime_debt",
        "current_status": "deferred",
        "priority": "P4",
        "required_before_module_completion": False,
        "required_before_integration_test": False,
        "required_before_runtime": True,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["future_runtime_debt_registry"],
        "recommended_phase": "Phase-Midplatform-Runtime-Adapter-Planning-v1-001",
    },
    {
        "work_id": "whitebox_runtime_integration",
        "work_name": "Whitebox Runtime Integration",
        "category": "future_runtime_debt",
        "current_status": "deferred",
        "priority": "P4",
        "required_before_module_completion": False,
        "required_before_integration_test": False,
        "required_before_runtime": True,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["runtime_adapter_implementation"],
        "recommended_phase": "Phase-Midplatform-Whitebox-Runtime-Integration-Planning-v1-001",
    },
    {
        "work_id": "real_execution_preauthorization_gate",
        "work_name": "Real Execution Preauthorization Gate",
        "category": "required_before_runtime",
        "current_status": "deferred",
        "priority": "P4",
        "required_before_module_completion": False,
        "required_before_integration_test": False,
        "required_before_runtime": True,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["integration_test_planning"],
        "recommended_phase": "Phase-Midplatform-Real-Execution-Preauthorization-Planning-v1-001",
    },
    {
        "work_id": "task_center_drive_brain_intelligence",
        "work_name": "Task Center Drive Brain Intelligence",
        "category": "future_design",
        "current_status": "future",
        "priority": "future",
        "required_before_module_completion": False,
        "required_before_integration_test": False,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["task_manager_core_orchestration_skeleton"],
        "recommended_phase": "Phase-Midplatform-Task-Center-Intelligence-Planning-v1-001",
    },
    {
        "work_id": "time_bound_task_elasticity_tradeoff",
        "work_name": "Time-Bound Task Elasticity Tradeoff",
        "category": "future_design",
        "current_status": "future",
        "priority": "future",
        "required_before_module_completion": False,
        "required_before_integration_test": False,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["task_center_drive_brain_intelligence"],
        "recommended_phase": "Phase-Midplatform-Time-Bound-Task-Elasticity-Planning-v1-001",
    },
    {
        "work_id": "health_memory_world_model_hooks",
        "work_name": "Health Signal Memory World Model Entry Hooks",
        "category": "future_design",
        "current_status": "future",
        "priority": "future",
        "required_before_module_completion": False,
        "required_before_integration_test": False,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["task_manager_core_orchestration_skeleton"],
        "recommended_phase": "Phase-Midplatform-Health-Memory-World-Model-Hooks-Planning-v1-001",
    },
    {
        "work_id": "distributed_ready_field_alignment",
        "work_name": "Distributed Ready Field Alignment",
        "category": "planning",
        "current_status": "planned",
        "priority": "P3",
        "required_before_module_completion": False,
        "required_before_integration_test": True,
        "required_before_runtime": False,
        "can_defer": True,
        "blocker_now": False,
        "dependency_refs": ["module_integration_planning"],
        "recommended_phase": "Phase-Midplatform-Distributed-Ready-Field-Alignment-Planning-v1-001",
    },
)

MODULE_COMPLETION_CANDIDATES: Tuple[Dict[str, str], ...] = (
    {"candidate_id": "module_boundary_registry", "assessment": "plan_next", "priority": "P2"},
    {"candidate_id": "candidate_lifecycle_manager", "assessment": "plan_next", "priority": "P2"},
    {"candidate_id": "evidence_record_approval_permission_alignment", "assessment": "plan_with_integration", "priority": "P2"},
    {"candidate_id": "task_manager_core_orchestration_skeleton", "assessment": "continue_construction", "priority": "P2"},
    {"candidate_id": "health_memory_world_model_hooks", "assessment": "defer_future", "priority": "future"},
    {"candidate_id": "distributed_ready_field_alignment", "assessment": "plan_after_integration", "priority": "P3"},
)
