"""Synthetic fixtures for Cognitive Learning controlled implementation v1."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple

from capabilities.midplatform.core.cognitive_learning.cognitive_learning_io_types_v1 import (
    CognitiveLearningInputV1,
)


@dataclass(frozen=True)
class CognitiveLearningFixtureCaseV1:
    case_id: str
    description: str
    request: CognitiveLearningInputV1
    expected_learning_kind: str
    expected_generalization_level: str
    expected_admission_state: str
    expected_parameter_update: bool
    expected_contradiction: bool
    expected_counterexample: bool
    expected_revision: bool
    expected_supersession: bool
    expected_revocation: bool
    expected_expiration: bool
    expected_negative_guards: Dict[str, bool]
    synthetic_only: bool = True


def _base_input(case_id: str) -> CognitiveLearningInputV1:
    return CognitiveLearningInputV1(
        scenario_id=case_id,
        source_experience_refs=(f"experience:{case_id}:1",),
        source_memory_refs=(f"memory:{case_id}:1",),
        outcome_refs=(f"outcome:{case_id}:1",),
        feedback_refs=(f"feedback:{case_id}:1",),
        contradiction_refs=(f"contradiction:{case_id}:1",)
        if case_id in {"L06", "L31", "L32"}
        else (),
        counterexample_refs=(f"counterexample:{case_id}:1",)
        if case_id in {"L06", "L25"}
        else (),
        context_refs=(f"context:{case_id}:1",),
        intent_refs=(f"intent:{case_id}:1",),
        hypothesis_refs=(f"hypothesis:{case_id}:1",),
        current_world_refs=(f"current_world:{case_id}:1",),
        cognitive_state_vector_refs=(f"state_vector:{case_id}:1",),
        regulation_refs=(f"regulation:{case_id}:1",),
        causal_refs=(f"causal:{case_id}:1",) if case_id == "L22" else (),
        semantic_compression_ref=None,
        affective_memory_summary_ref=None,
        emotional_context_summary_ref=None,
        user_specific_learning_candidate=True,
        sensitivity_level="HIGH_SENSITIVITY" if case_id == "L27" else "NORMAL",
        synthetic_only=True,
        candidate_only=True,
    )


def _neg() -> Dict[str, bool]:
    return {
        "learning_can_create_fact": False,
        "learning_can_mutate_memory": False,
        "learning_can_mutate_context": False,
        "learning_can_mutate_pcn": False,
        "learning_can_mutate_intent": False,
        "learning_can_mutate_attention": False,
        "learning_can_declare_hypothesis_truth": False,
        "learning_can_mutate_current_world": False,
        "learning_can_mutate_state_vector": False,
        "learning_can_mutate_causal": False,
        "learning_can_mutate_regulation_parameter": False,
        "learning_can_bypass_parameter_bounds": False,
        "learning_can_activate_parameter": False,
        "learning_can_activate_genome": False,
        "learning_can_mutate_self": False,
        "learning_can_mutate_personality": False,
        "learning_can_mutate_emotion": False,
        "learning_can_create_task": False,
        "learning_can_control_device": False,
        "learning_can_run_scheduler": False,
        "learning_can_call_model": False,
        "database_write": False,
        "vector_store_write": False,
        "embedding_execution": False,
        "runtime_training": False,
        "model_weight_update": False,
        "source_owner_mutation": False,
        "cross_user_transfer": False,
        "semantic_compression_execution": False,
        "real_side_effect": False,
        "planning_only": True,
    }


def get_cognitive_learning_fixtures_v1() -> Tuple[CognitiveLearningFixtureCaseV1, ...]:
    defs = (
        (
            "L01",
            "single success instance-only",
            "SUCCESS_PATTERN",
            "INSTANCE_ONLY",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L02",
            "same-source repetition no fake multiplication",
            "SUCCESS_PATTERN",
            "INSTANCE_ONLY",
            "ELIGIBLE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L03",
            "diverse-context repeated success",
            "SUCCESS_PATTERN",
            "LOCAL_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L04",
            "single failure no permanent rule",
            "FAILURE_PATTERN",
            "INSTANCE_ONLY",
            "ELIGIBLE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L05",
            "repeated failure pattern",
            "FAILURE_PATTERN",
            "LOCAL_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L06",
            "contradiction",
            "CONTRADICTION_PATTERN",
            "INSTANCE_ONLY",
            "CONTESTED",
            True,
            True,
            True,
            False,
            False,
            False,
            False,
        ),
        (
            "L07",
            "explicit user positive feedback",
            "USER_FEEDBACK_PATTERN",
            "LOCAL_CONTEXT",
            "ELIGIBLE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L08",
            "explicit user negative feedback",
            "NEGATIVE_EVIDENCE_PATTERN",
            "LOCAL_CONTEXT",
            "ELIGIBLE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L09",
            "stale feedback",
            "USER_FEEDBACK_PATTERN",
            "INSTANCE_ONLY",
            "INSUFFICIENT_EVIDENCE",
            True,
            False,
            False,
            False,
            False,
            False,
            True,
        ),
        (
            "L10",
            "revoked source memory",
            "NEGATIVE_EVIDENCE_PATTERN",
            "INSTANCE_ONLY",
            "REVOKED",
            True,
            False,
            False,
            False,
            False,
            True,
            False,
        ),
        (
            "L11",
            "superseded experience",
            "TEMPORAL_PATTERN",
            "INSTANCE_ONLY",
            "SUPERSEDED",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L12",
            "high salience weak evidence",
            "SUCCESS_PATTERN",
            "INSTANCE_ONLY",
            "INSUFFICIENT_EVIDENCE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L13",
            "low salience repeated evidence",
            "SUCCESS_PATTERN",
            "LOCAL_CONTEXT",
            "ELIGIBLE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L14",
            "preference pattern",
            "PREFERENCE_PATTERN",
            "LOCAL_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L15",
            "relationship-specific pattern",
            "SOCIAL_PATTERN",
            "RELATIONSHIP_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L16",
            "role-specific pattern",
            "CONTEXT_DEPENDENT_PATTERN",
            "ROLE_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L17",
            "context-specific pattern",
            "CONTEXT_DEPENDENT_PATTERN",
            "LOCAL_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L18",
            "resource-constrained regulation outcome",
            "RESOURCE_PATTERN",
            "LOCAL_CONTEXT",
            "ELIGIBLE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L19",
            "attention pattern evidence",
            "ATTENTION_PATTERN",
            "LOCAL_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L20",
            "hypothesis resolution evidence",
            "HYPOTHESIS_RESOLUTION_PATTERN",
            "LOCAL_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L21",
            "unresolved hypothesis",
            "UNRESOLVED_PATTERN",
            "INSTANCE_ONLY",
            "CONTESTED",
            True,
            True,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L22",
            "causal support reference present",
            "SUCCESS_PATTERN",
            "LOCAL_CONTEXT",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L23",
            "causal support absent",
            "SUCCESS_PATTERN",
            "INSTANCE_ONLY",
            "ELIGIBLE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L24",
            "parameter update candidate creation",
            "REGULATION_EFFECT_PATTERN",
            "LOCAL_CONTEXT",
            "PARAMETER_UPDATE_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L25",
            "parameter bounds prevent proposed update",
            "REGULATION_EFFECT_PATTERN",
            "LOCAL_CONTEXT",
            "CONTESTED",
            True,
            False,
            True,
            False,
            False,
            False,
            False,
        ),
        (
            "L26",
            "genome activation forbidden",
            "REGULATION_EFFECT_PATTERN",
            "LOCAL_CONTEXT",
            "PARAMETER_UPDATE_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L27",
            "privacy-sensitive learning",
            "USER_FEEDBACK_PATTERN",
            "INSTANCE_ONLY",
            "NEEDS_CONFIRMATION",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L28",
            "semantic compression ref missing learning still proceeds",
            "SUCCESS_PATTERN",
            "INSTANCE_ONLY",
            "LEARNING_CANDIDATE_READY",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L29",
            "duplicate learning evidence",
            "SUCCESS_PATTERN",
            "INSTANCE_ONLY",
            "REJECTED",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L30",
            "duplicate parameter update candidate",
            "REGULATION_EFFECT_PATTERN",
            "LOCAL_CONTEXT",
            "REJECTED",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "L31",
            "revision supersession",
            "CONTRADICTION_PATTERN",
            "LOCAL_CONTEXT",
            "REVISED",
            True,
            True,
            False,
            True,
            True,
            False,
            False,
        ),
        (
            "L32",
            "revocation expiration",
            "NEGATIVE_EVIDENCE_PATTERN",
            "INSTANCE_ONLY",
            "REVOKED",
            True,
            True,
            False,
            False,
            False,
            True,
            True,
        ),
    )
    return tuple(
        CognitiveLearningFixtureCaseV1(
            case_id=sid,
            description=desc,
            request=_base_input(sid),
            expected_learning_kind=kind,
            expected_generalization_level=level,
            expected_admission_state=state,
            expected_parameter_update=parameter_update,
            expected_contradiction=contradiction,
            expected_counterexample=counterexample,
            expected_revision=revision,
            expected_supersession=supersession,
            expected_revocation=revocation,
            expected_expiration=expiration,
            expected_negative_guards=_neg(),
        )
        for sid, desc, kind, level, state, parameter_update, contradiction, counterexample, revision, supersession, revocation, expiration in defs
    )
