from __future__ import annotations

from typing import Any, Dict, Tuple

from .model_contract_repository_types_v1 import (
    CapabilityContractV1,
    EvidenceContractV1,
    LoaderContractV1,
    ModelAssetContractV1,
    ProviderAdapterContractV1,
    to_dict,
)


def build_model_contract_repository_v1() -> Dict[str, Dict[str, Dict[str, Any]]]:
    evidence_visual = EvidenceContractV1(
        evidence_contract_id="evidence:visual-detection-candidate:v1",
        evidence_kind="VISUAL_DETECTION_CANDIDATE",
        evidence_version="v1",
        schema_ref="VisualDetectionEvidenceCandidateV1",
        candidate_only=True,
        truth_declared=False,
        fact_admitted=False,
    )
    loader_yolov5 = LoaderContractV1(
        loader_contract_id="loader:yolov5:torch-hub-local:v1",
        loader_kind="torch_hub_yolov5_custom_local_weights",
        loader_version="v1",
        runtime_framework="torch",
        framework_version_constraints=("torch==2.8.0", "torchvision==0.23.0"),
        supported_weight_formats=("pt",),
        local_source_package_required=True,
        local_source_package_ref=None,
        required_dependencies=("torch", "torchvision"),
        supported_devices=("cpu", "cuda", "mps"),
        network_allowed=False,
        automatic_download_allowed=False,
        loader_entrypoint_ref="torch.hub.load(source=local, model=custom)",
        compatibility_constraints=("local_yolov5_source_tree_required", "legacy_models_yolo_Model_class_required"),
    )
    loader_ultralytics = LoaderContractV1(
        loader_contract_id="loader:ultralytics:yolo:v1",
        loader_kind="ultralytics_yolo",
        loader_version="v1",
        runtime_framework="ultralytics",
        framework_version_constraints=(">=8.0.0",),
        supported_weight_formats=("pt", "onnx"),
        local_source_package_required=False,
        local_source_package_ref=None,
        required_dependencies=("ultralytics",),
        supported_devices=("cpu", "cuda", "mps"),
        network_allowed=False,
        automatic_download_allowed=False,
        loader_entrypoint_ref="ultralytics.YOLO",
        compatibility_constraints=("checkpoint_must_be_ultralytics_compatible",),
    )
    loader_roboflow = LoaderContractV1(
        loader_contract_id="loader:roboflow:workflow-api:v1",
        loader_kind="external_workflow_api",
        loader_version="v1",
        runtime_framework="inference_sdk",
        framework_version_constraints=("inference-sdk:version-must-be-pinned-by-environment",),
        supported_weight_formats=("provider_managed",),
        local_source_package_required=False,
        local_source_package_ref=None,
        required_dependencies=("inference-sdk",),
        supported_devices=("remote",),
        network_allowed=True,
        automatic_download_allowed=False,
        loader_entrypoint_ref="inference_sdk.InferenceHTTPClient.run_workflow",
        compatibility_constraints=("workflow_input:image", "provider_managed_weights"),
    )
    adapter_yolo = ProviderAdapterContractV1(
        provider_adapter_id="adapter:yolo:visual-evidence:v1",
        provider_family="yolo",
        adapter_version="v1",
        input_contract="RawFrameReferenceV1",
        native_output_contract="detections_xyxy_conf_cls",
        canonical_output_contract_refs=(evidence_visual.evidence_contract_id,),
        supported_loader_contracts=(loader_yolov5.loader_contract_id, loader_ultralytics.loader_contract_id),
        error_namespace="VISION_PROVIDER_ADAPTER_ERRORS_V1",
        trace_requirements=("model_asset", "loader_contract", "provider_output", "source_frame", "provenance"),
        candidate_only_output=True,
    )
    adapter_roboflow = ProviderAdapterContractV1(
        provider_adapter_id="adapter:roboflow:vision-evidence:v1",
        provider_family="roboflow",
        adapter_version="v1",
        input_contract="RawFrameReferenceV1",
        native_output_contract="roboflow_workflow_result_private",
        canonical_output_contract_refs=(evidence_visual.evidence_contract_id,),
        supported_loader_contracts=(loader_roboflow.loader_contract_id,),
        error_namespace="VISION_PROVIDER_ADAPTER_ERRORS_V1",
        trace_requirements=("provider", "workflow", "model_asset", "source_frame", "provider_output", "provenance"),
        candidate_only_output=True,
    )
    capability_detection = CapabilityContractV1(
        capability_contract_id="capability:object-detection:v1",
        capability_kind="OBJECT_DETECTION",
        capability_version="v1",
        execution_properties=("full_frame", "ROI", "fixed_class", "bounded_session"),
        required_input_contract="RawFrameReferenceV1",
        canonical_evidence_contract_refs=(evidence_visual.evidence_contract_id,),
    )
    assets = (
        ModelAssetContractV1(
            model_asset_id="model-asset:yolov5n:weights-v1",
            model_family="yolo",
            model_name="yolov5n",
            model_version="v5",
            weights_version="pinned-local-v1",
            weight_format="pt",
            weights_path="vision/detection/yolo/yolov5n.pt",
            checksum="4f180cf23ba0717ada0badd6c685026d73d48f184d00fc159c2641284b2ac0a3",
            source="pinned_local_manifest",
            license="GNU-GPL-3.0-or-later-or-upstream-review-required",
            provider_family="yolo",
            declared_loader_contract_id=loader_yolov5.loader_contract_id,
            declared_capability_contract_ids=(capability_detection.capability_contract_id,),
            declared_evidence_contract_ids=(evidence_visual.evidence_contract_id,),
            deployment_profile_refs=(
                "deployment:mac-local-test:v1",
                "deployment:jetson-edge:v1",
                "deployment:cpu-fallback:v1",
                "deployment:future-wearable-edge:v1",
            ),
            benchmark_profile_refs=("benchmark:luna-first-person-vision:v1",),
            status="REGISTERED",
        ),
        ModelAssetContractV1(
            model_asset_id="model-asset:yolov5n:weights-v2",
            model_family="yolo",
            model_name="yolov5n",
            model_version="v5",
            weights_version="alternate-v2",
            weight_format="pt",
            weights_path="vision/detection/yolo/yolov5n-v2.pt",
            checksum=None,
            source="registered_candidate",
            license=None,
            provider_family="yolo",
            declared_loader_contract_id=loader_yolov5.loader_contract_id,
            declared_capability_contract_ids=(capability_detection.capability_contract_id,),
            declared_evidence_contract_ids=(evidence_visual.evidence_contract_id,),
            deployment_profile_refs=(
                "deployment:mac-local-test:v1",
                "deployment:jetson-edge:v1",
                "deployment:cpu-fallback:v1",
                "deployment:future-wearable-edge:v1",
            ),
            benchmark_profile_refs=("benchmark:luna-first-person-vision:v1",),
            status="SUPPORTED",
        ),
        ModelAssetContractV1(
            model_asset_id="model-asset:yolo11n:weights-v1",
            model_family="yolo",
            model_name="yolo11n",
            model_version="v11",
            weights_version="registered-v1",
            weight_format="pt",
            weights_path="vision/detection/yolo/yolo11n.pt",
            checksum="0ebbc80d4a7680d14987a577cd21342b65ecfd94632bd9a8da63ae6417644ee1",
            source="registered_candidate",
            license=None,
            provider_family="yolo",
            declared_loader_contract_id=loader_ultralytics.loader_contract_id,
            declared_capability_contract_ids=(capability_detection.capability_contract_id,),
            declared_evidence_contract_ids=(evidence_visual.evidence_contract_id,),
            deployment_profile_refs=(
                "deployment:mac-local-test:v1",
                "deployment:jetson-edge:v1",
                "deployment:cpu-fallback:v1",
                "deployment:future-wearable-edge:v1",
            ),
            benchmark_profile_refs=("benchmark:luna-first-person-vision:v1",),
            status="SUPPORTED",
        ),
        ModelAssetContractV1(
            model_asset_id="model-asset:yolo26n:weights-v1",
            model_family="yolo",
            model_name="yolo26n",
            model_version="v26",
            weights_version="registered-v1",
            weight_format="pt",
            weights_path="vision/detection/yolo/yolo26n.pt",
            checksum=None,
            source="registered_candidate",
            license=None,
            provider_family="yolo",
            declared_loader_contract_id=loader_ultralytics.loader_contract_id,
            declared_capability_contract_ids=(capability_detection.capability_contract_id,),
            declared_evidence_contract_ids=(evidence_visual.evidence_contract_id,),
            deployment_profile_refs=(
                "deployment:mac-local-test:v1",
                "deployment:jetson-edge:v1",
                "deployment:cpu-fallback:v1",
                "deployment:future-wearable-edge:v1",
            ),
            benchmark_profile_refs=("benchmark:luna-first-person-vision:v1",),
            status="SUPPORTED",
        ),
        ModelAssetContractV1(
            model_asset_id="model-asset:rf-detr-small:roboflow-v1",
            model_family="rf_detr",
            model_name="rf-detr-small",
            model_version="workflow-declared-v1",
            weights_version="provider-managed-declared-v1",
            weight_format="provider_managed",
            weights_path="provider-managed:roboflow:lei-luan:custom-workflow",
            checksum=None,
            source="provider_governed_workflow_declaration",
            license="Roboflow/provider terms — review required",
            provider_family="roboflow",
            declared_loader_contract_id=loader_roboflow.loader_contract_id,
            declared_capability_contract_ids=(capability_detection.capability_contract_id,),
            declared_evidence_contract_ids=(evidence_visual.evidence_contract_id,),
            deployment_profile_refs=("deployment:roboflow:serverless:v1",),
            benchmark_profile_refs=("benchmark:luna-first-person-vision:v1",),
            status="SUPPORTED",
        ),
    )
    deployment_profiles = {
        "deployment:mac-local-test:v1": {
            "profile_id": "deployment:mac-local-test:v1",
            "profile_name": "MAC_LOCAL_TEST",
            "latency_ms": None,
            "fps": None,
            "ram_mb": None,
            "vram_mb": None,
            "power_w": None,
            "cold_start_ms": None,
            "model_size_mb": None,
            "supported_export_formats": ("pt", "onnx"),
            "deployment_status": "UNRESOLVED",
        },
        "deployment:jetson-edge:v1": {
            "profile_id": "deployment:jetson-edge:v1",
            "profile_name": "JETSON_EDGE",
            "latency_ms": None,
            "fps": None,
            "ram_mb": None,
            "vram_mb": None,
            "power_w": None,
            "cold_start_ms": None,
            "model_size_mb": None,
            "supported_export_formats": ("pt", "onnx", "engine"),
            "deployment_status": "UNRESOLVED",
        },
        "deployment:cpu-fallback:v1": {
            "profile_id": "deployment:cpu-fallback:v1",
            "profile_name": "CPU_FALLBACK",
            "latency_ms": None,
            "fps": None,
            "ram_mb": None,
            "vram_mb": None,
            "power_w": None,
            "cold_start_ms": None,
            "model_size_mb": None,
            "supported_export_formats": ("pt", "onnx"),
            "deployment_status": "UNRESOLVED",
        },
        "deployment:future-wearable-edge:v1": {
            "profile_id": "deployment:future-wearable-edge:v1",
            "profile_name": "FUTURE_WEARABLE_EDGE",
            "latency_ms": None,
            "fps": None,
            "ram_mb": None,
            "vram_mb": None,
            "power_w": None,
            "cold_start_ms": None,
            "model_size_mb": None,
            "supported_export_formats": ("onnx", "engine"),
            "deployment_status": "UNRESOLVED",
        },
        "deployment:roboflow:serverless:v1": {
            "profile_id": "deployment:roboflow:serverless:v1",
            "profile_name": "ROBOFLOW_SERVERLESS_CLOUD",
            "latency_ms": None,
            "fps": None,
            "ram_mb": None,
            "vram_mb": None,
            "power_w": None,
            "cold_start_ms": None,
            "model_size_mb": None,
            "supported_export_formats": (),
            "deployment_status": "DECLARED_EXTERNAL_PROVIDER",
        },
    }
    benchmark_profiles = {
        "benchmark:luna-first-person-vision:v1": {
            "profile_id": "benchmark:luna-first-person-vision:v1",
            "profile_name": "LUNA_FIRST_PERSON_VISION_V1",
            "metrics": (
                "critical_obstacle_recall",
                "person_recall",
                "vehicle_recall",
                "small_object_recall",
                "false_positive_rate",
                "task_relative_evidence_sufficiency_success",
                "time_to_sufficient_evidence",
                "latency",
                "fps",
                "memory",
                "power",
            ),
            "status": "UNRESOLVED",
        },
    }
    license_profiles = {
        "model-asset:yolov5n:weights-v1": {
            "license_type": "GNU-GPL-3.0-or-later-or-upstream-review-required",
            "commercial_use_constraints": "REQUIRES_LICENSE_REVIEW",
            "enterprise_license_required_candidate": None,
            "license_source_ref": "existing_yolov5_manifest_and_prior_review",
        },
        "model-asset:yolov5n:weights-v2": {
            "license_type": "UNKNOWN",
            "commercial_use_constraints": "REQUIRES_LICENSE_REVIEW",
            "enterprise_license_required_candidate": None,
            "license_source_ref": "not_verified_in_repository",
        },
        "model-asset:yolo11n:weights-v1": {
            "license_type": "UNKNOWN",
            "commercial_use_constraints": "REQUIRES_LICENSE_REVIEW",
            "enterprise_license_required_candidate": None,
            "license_source_ref": "not_verified_in_repository",
        },
        "model-asset:yolo26n:weights-v1": {
            "license_type": "UNKNOWN",
            "commercial_use_constraints": "REQUIRES_LICENSE_REVIEW",
            "enterprise_license_required_candidate": None,
            "license_source_ref": "not_verified_in_repository",
        },
        "model-asset:rf-detr-small:roboflow-v1": {
            "license_type": "Roboflow/provider terms — unresolved",
            "commercial_use_constraints": "REQUIRES_LICENSE_REVIEW",
            "enterprise_license_required_candidate": None,
            "license_source_ref": "provider_declaration_required",
        },
    }
    production_vision_routes = {
        "model-asset:yolov5n:weights-v1": {
            "role": "LEGACY_REFERENCE",
            "runtime_priority": "LOW",
            "benchmark_candidate": False,
            "do_not_invest_further": True,
            "production_admission": "NOT_YET_PROVEN",
            "best_fit": False,
        },
        "model-asset:yolov5n:weights-v2": {
            "role": "LEGACY_REFERENCE",
            "runtime_priority": "LOW",
            "benchmark_candidate": False,
            "do_not_invest_further": True,
            "production_admission": "NOT_YET_PROVEN",
            "best_fit": False,
        },
        "model-asset:yolo11n:weights-v1": {
            "role": "STABILITY_COMPARATOR",
            "runtime_priority": "MEDIUM",
            "benchmark_candidate": True,
            "do_not_invest_further": False,
            "production_admission": "NOT_YET_PROVEN",
            "best_fit": False,
        },
        "model-asset:yolo26n:weights-v1": {
            "role": "PRIMARY_CANDIDATE",
            "runtime_priority": "HIGH",
            "benchmark_candidate": True,
            "do_not_invest_further": False,
            "production_admission": "NOT_YET_PROVEN",
            "best_fit": False,
        },
        "model-asset:rf-detr-small:roboflow-v1": {
            "role": "EXTERNAL_PROVIDER_CANDIDATE",
            "runtime_priority": "UNRESOLVED",
            "benchmark_candidate": True,
            "do_not_invest_further": False,
            "production_admission": "NOT_YET_PROVEN",
            "best_fit": False,
        },
    }
    return {
        "model_assets": {item.model_asset_id: to_dict(item) for item in assets},
        "loader_contracts": {
            loader_yolov5.loader_contract_id: to_dict(loader_yolov5),
            loader_ultralytics.loader_contract_id: to_dict(loader_ultralytics),
            loader_roboflow.loader_contract_id: to_dict(loader_roboflow),
        },
        "provider_adapter_contracts": {
            adapter_yolo.provider_adapter_id: to_dict(adapter_yolo),
            adapter_roboflow.provider_adapter_id: to_dict(adapter_roboflow),
        },
        "capability_contracts": {capability_detection.capability_contract_id: to_dict(capability_detection)},
        "evidence_contracts": {evidence_visual.evidence_contract_id: to_dict(evidence_visual)},
        "local_source_packages": {},
        "deployment_profiles": deployment_profiles,
        "benchmark_profiles": benchmark_profiles,
        "license_profiles": license_profiles,
        "production_vision_routes": production_vision_routes,
    }
