"""Synthetic fixtures for Cognitive Memory & Experience controlled implementation v1."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple

from capabilities.midplatform.core.cognitive_memory_experience.memory_io_types_v1 import (
    CognitiveMemoryExperienceInputV1,
)


@dataclass(frozen=True)
class CognitiveMemoryExperienceFixtureCaseV1:
    case_id: str
    description: str
    request: CognitiveMemoryExperienceInputV1
    expected_memory_type: str
    expected_admission_state: str
    expected_retrieval: bool
    expected_learning_evidence: bool
    expected_personality_evidence: bool
    expected_revision: bool
    expected_supersession: bool
    expected_revocation: bool
    expected_expiration: bool
    expected_negative_guards: Dict[str, bool]
    synthetic_only: bool = True


def _base_input(case_id: str) -> CognitiveMemoryExperienceInputV1:
    return CognitiveMemoryExperienceInputV1(
        scenario_id=case_id,
        cycle_id=f"cycle:{case_id}",
        root_cycle_trace_id=f"trace:{case_id}:root_cycle",
        context_refs=(f"context:{case_id}:1",),
        field_refs=(f"field:{case_id}:1",),
        pcn_refs=(f"pcn:{case_id}:1",),
        intent_refs=(f"intent:{case_id}:1",),
        attention_refs=(f"attention:{case_id}:1",),
        hypothesis_refs=(f"hypothesis:{case_id}:1",),
        current_world_ref=f"current_world:{case_id}:1",
        cognitive_state_vector_ref=f"state_vector:{case_id}:1",
        regulation_candidate_ref=f"regulation:{case_id}:1",
        causal_refs=(f"causal:{case_id}:1",),
        decision_refs_optional=(f"decision:{case_id}:1",),
        action_refs_optional=(f"action:{case_id}:1",),
        execution_result_refs_optional=(f"execution:{case_id}:1",),
        user_feedback_refs=(f"feedback:{case_id}:1",),
        source_evidence_refs=(f"evidence:{case_id}:1", f"evidence:{case_id}:2"),
        prior_memory_refs=(f"prior_memory:{case_id}:1",),
        synthetic_only=True,
        candidate_only=True,
    )


def _neg() -> Dict[str, bool]:
    return {
        "memory_can_create_fact_directly": False,
        "memory_can_mutate_field": False,
        "memory_can_mutate_context": False,
        "memory_can_mutate_pcn": False,
        "memory_can_mutate_intent": False,
        "memory_can_mutate_attention": False,
        "memory_can_mutate_hypothesis": False,
        "memory_can_mutate_current_world": False,
        "memory_can_mutate_state_vector": False,
        "memory_can_mutate_regulation_parameter": False,
        "memory_can_activate_parameter_genome": False,
        "memory_can_execute_learning": False,
        "memory_can_mutate_personality": False,
        "memory_can_create_task": False,
        "memory_can_control_device": False,
        "memory_can_run_scheduler": False,
        "memory_can_call_model": False,
        "database_write": False,
        "vector_store_write": False,
        "embedding_execution": False,
        "runtime_execution": False,
        "model_call": False,
        "source_owner_mutation": False,
        "real_side_effect": False,
        "synthetic_only": True,
        "candidate_only": True,
        "learning_execution": False,
        "personality_mutation": False,
    }


def get_cognitive_memory_experience_fixtures_v1() -> Tuple[
    CognitiveMemoryExperienceFixtureCaseV1, ...
]:
    defs = (
        (
            "M01",
            "normal episodic candidate",
            "EPISODIC",
            "ELIGIBLE",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M02",
            "repeated event not automatic fact",
            "EPISODIC",
            "TEMPORARY",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M03",
            "high salience",
            "EPISODIC",
            "ELIGIBLE",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M04",
            "temporary low salience",
            "ENVIRONMENTAL_CONTEXT",
            "TEMPORARY",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M05",
            "unresolved hypothesis",
            "UNRESOLVED_EXPERIENCE",
            "CONTESTED",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M06",
            "conflicting hypotheses",
            "UNRESOLVED_EXPERIENCE",
            "CONTESTED",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M07",
            "contradiction",
            "EPISODIC",
            "CONTESTED",
            False,
            False,
            False,
            False,
            False,
            True,
            False,
        ),
        (
            "M08",
            "supersession",
            "SEMANTIC",
            "SUPERSEDED",
            False,
            False,
            False,
            False,
            True,
            False,
            False,
        ),
        (
            "M09",
            "revision",
            "SEMANTIC",
            "REVISED",
            False,
            False,
            False,
            True,
            False,
            False,
            False,
        ),
        (
            "M10",
            "revocation",
            "SEMANTIC",
            "REVOKED",
            False,
            False,
            False,
            False,
            False,
            True,
            False,
        ),
        (
            "M11",
            "expiration",
            "ENVIRONMENTAL_CONTEXT",
            "EXPIRED",
            False,
            False,
            False,
            False,
            False,
            False,
            True,
        ),
        (
            "M12",
            "user confirms",
            "PREFERENCE",
            "ADMITTED_CANDIDATE",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M13",
            "user rejects",
            "PREFERENCE",
            "REJECTED",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M14",
            "preference candidate",
            "PREFERENCE",
            "NEEDS_CONFIRMATION",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M15",
            "relationship candidate",
            "RELATIONAL",
            "NEEDS_CONFIRMATION",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M16",
            "self evidence no personality mutation",
            "SELF_RELATED",
            "NEEDS_CONFIRMATION",
            False,
            False,
            True,
            False,
            False,
            False,
            False,
        ),
        (
            "M17",
            "context retrieval candidate",
            "EPISODIC",
            "ELIGIBLE",
            True,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M18",
            "pcn influence",
            "RELATIONAL",
            "ELIGIBLE",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M19",
            "intent influence",
            "PREFERENCE",
            "ELIGIBLE",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M20",
            "state formation influence",
            "UNRESOLVED_EXPERIENCE",
            "ELIGIBLE",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M21",
            "regulation outcome not parameter update",
            "TASK_EXPERIENCE",
            "ELIGIBLE",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M22",
            "learning evidence only",
            "TASK_EXPERIENCE",
            "ELIGIBLE",
            False,
            True,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M23",
            "duplicate guard",
            "EPISODIC",
            "REJECTED",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M24",
            "reverse provenance",
            "EPISODIC",
            "ELIGIBLE",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M25",
            "high sensitivity stronger gate",
            "SELF_RELATED",
            "NEEDS_CONFIRMATION",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
        (
            "M26",
            "field contradicts recalled memory",
            "EPISODIC",
            "CONTESTED",
            True,
            False,
            False,
            False,
            False,
            True,
            False,
        ),
        (
            "M27",
            "stale current-world context",
            "ENVIRONMENTAL_CONTEXT",
            "EXPIRED",
            True,
            False,
            False,
            False,
            False,
            False,
            True,
        ),
        (
            "M28",
            "multiple candidate memories coexist",
            "UNRESOLVED_EXPERIENCE",
            "CONTESTED",
            False,
            False,
            False,
            False,
            False,
            False,
            False,
        ),
    )
    return tuple(
        CognitiveMemoryExperienceFixtureCaseV1(
            case_id=sid,
            description=desc,
            request=_base_input(sid),
            expected_memory_type=memory_type,
            expected_admission_state=admission,
            expected_retrieval=retrieval,
            expected_learning_evidence=learning,
            expected_personality_evidence=personality,
            expected_revision=revision,
            expected_supersession=supersession,
            expected_revocation=revocation,
            expected_expiration=expiration,
            expected_negative_guards=_neg(),
        )
        for sid, desc, memory_type, admission, retrieval, learning, personality, revision, supersession, revocation, expiration in defs
    )
