# -*- coding: utf-8 -*-
"""Field State Reducer controlled dryrun cases v1."""

from __future__ import annotations

from typing import Dict, Tuple

from capabilities.midplatform.core.field_state_reducer.field_state_reducer_controlled_dryrun_types_v1 import (
    FieldStateReducerDryRunCaseV1,
)


def _case(
    case_id: str,
    case_type: str,
    fixture_refs: Tuple[str, ...],
    input_overrides: Dict[str, object],
    expected_validation: bool,
    expected_error_code: str | None,
    deterministic_comparison_required: bool,
) -> FieldStateReducerDryRunCaseV1:
    return FieldStateReducerDryRunCaseV1(
        case_id=case_id,
        case_type=case_type,
        fixture_refs=fixture_refs,
        input_overrides=input_overrides,
        expected_validation=expected_validation,
        expected_error_code=expected_error_code,
        expected_reduction_decision="skeleton_no_state_change",
        expected_resulting_state=None,
        expected_state_mutation_executed=False,
        expected_runtime_execution=False,
        deterministic_comparison_required=deterministic_comparison_required,
    )


FIELD_STATE_REDUCER_CONTROLLED_DRYRUN_CASES_V1: Tuple[
    FieldStateReducerDryRunCaseV1, ...
] = (
    _case(
        case_id="baseline_all_fixtures_case",
        case_type="positive",
        fixture_refs=(
            "road_accessible_event",
            "construction_notice_event",
            "barrier_visual_event",
            "road_blocked_event",
            "temporary_passage_event",
            "conflict_event",
            "overlay_expired_event",
            "refresh_evidence_event",
            "road_reopened_event",
        ),
        input_overrides={},
        expected_validation=True,
        expected_error_code=None,
        deterministic_comparison_required=True,
    ),
    _case(
        case_id="repeated_identical_input_case",
        case_type="positive",
        fixture_refs=(
            "road_accessible_event",
            "construction_notice_event",
            "barrier_visual_event",
            "road_blocked_event",
            "temporary_passage_event",
            "conflict_event",
            "overlay_expired_event",
            "refresh_evidence_event",
            "road_reopened_event",
        ),
        input_overrides={},
        expected_validation=True,
        expected_error_code=None,
        deterministic_comparison_required=True,
    ),
    _case(
        case_id="reversed_input_order_case",
        case_type="positive",
        fixture_refs=(
            "road_reopened_event",
            "refresh_evidence_event",
            "overlay_expired_event",
            "conflict_event",
            "temporary_passage_event",
            "road_blocked_event",
            "barrier_visual_event",
            "construction_notice_event",
            "road_accessible_event",
        ),
        input_overrides={},
        expected_validation=True,
        expected_error_code=None,
        deterministic_comparison_required=True,
    ),
    _case(
        case_id="single_event_case",
        case_type="positive",
        fixture_refs=("road_accessible_event",),
        input_overrides={},
        expected_validation=True,
        expected_error_code=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="conflict_fixture_case",
        case_type="positive",
        fixture_refs=("conflict_event", "road_blocked_event"),
        input_overrides={},
        expected_validation=True,
        expected_error_code=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="overlay_fixture_case",
        case_type="positive",
        fixture_refs=("temporary_passage_event", "overlay_expired_event"),
        input_overrides={},
        expected_validation=True,
        expected_error_code=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="non_admitted_event_rejection_case",
        case_type="negative",
        fixture_refs=("road_accessible_event",),
        input_overrides={"set_first_event_admitted": False},
        expected_validation=False,
        expected_error_code="non_admitted_event_not_allowed",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="raw_observation_rejection_case",
        case_type="negative",
        fixture_refs=("road_accessible_event",),
        input_overrides={"set_first_event_raw_observation": True},
        expected_validation=False,
        expected_error_code="raw_observation_not_allowed",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="missing_temporal_snapshot_case",
        case_type="negative",
        fixture_refs=("road_accessible_event",),
        input_overrides={"temporal_snapshot": {}},
        expected_validation=False,
        expected_error_code="missing_temporal_snapshot",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="missing_version_snapshot_case",
        case_type="negative",
        fixture_refs=("road_accessible_event",),
        input_overrides={"version_snapshot": None},
        expected_validation=False,
        expected_error_code="missing_version_snapshot",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="unstable_event_id_case",
        case_type="negative",
        fixture_refs=("road_accessible_event", "construction_notice_event"),
        input_overrides={"duplicate_event_id": "dup_event"},
        expected_validation=False,
        expected_error_code="unstable_event_order",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="direct_mutation_request_case",
        case_type="negative",
        fixture_refs=("road_accessible_event",),
        input_overrides={"direct_state_mutation_requested": True},
        expected_validation=False,
        expected_error_code="direct_state_mutation_forbidden",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="provider_recall_request_case",
        case_type="negative",
        fixture_refs=("road_accessible_event",),
        input_overrides={"no_provider_recall": False},
        expected_validation=False,
        expected_error_code="provider_recall_forbidden",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="external_lookup_request_case",
        case_type="negative",
        fixture_refs=("road_accessible_event",),
        input_overrides={"no_external_lookup": False},
        expected_validation=False,
        expected_error_code="external_lookup_forbidden",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="action_trigger_request_case",
        case_type="negative",
        fixture_refs=("road_accessible_event",),
        input_overrides={"no_action_trigger": False},
        expected_validation=False,
        expected_error_code="action_trigger_forbidden",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="event_mutation_guard_case",
        case_type="negative",
        fixture_refs=(
            "road_accessible_event",
            "construction_notice_event",
            "barrier_visual_event",
            "road_blocked_event",
            "temporary_passage_event",
            "conflict_event",
            "overlay_expired_event",
            "refresh_evidence_event",
            "road_reopened_event",
        ),
        input_overrides={
            "set_first_event_admitted": False,
            "mutation_guard_check_only": True,
        },
        expected_validation=False,
        expected_error_code="non_admitted_event_not_allowed",
        deterministic_comparison_required=False,
    ),
)
