"""Static registry for the candidate-only A → B-CR → A bridge."""

from __future__ import annotations

from capabilities.midplatform.core.cognitive_flow.integration.authority_grant_mechanical_command_controlled.authority_grant_mechanical_command_registry_v1 import (
    A_AUTHORITIES,
    B_AUTHORITIES,
    LOOP_COMMAND_CAPABILITY,
    MECHANICAL_COMMANDS,
    ROLE_A,
    ROLE_B,
)


PHASE = "Phase-Luna-A-To-B-Contingency-Reasoning-Return-Bridge-Controlled-Implementation-v1-001"
B_CR_AUTHORITIES = B_AUTHORITIES
REQUIRED_A_TRIGGER_AUTHORITY = "REQUEST_B"
RESULT_EVALUATION_AUTHORITY = "JUDGE_EVIDENCE_RELEVANCE"

B_RESULT_STATUSES = (
    "COMPLETED_WITH_CANDIDATES",
    "PARTIAL_RESULT",
    "BOUNDED_UNCERTAINTY_REMAINS",
    "STALE_SOURCE_STATE",
    "GRANT_REVOKED",
    "RESOURCE_LIMIT",
    "SAFETY_LIMIT",
    "NO_USEFUL_CONTINGENCY",
)

EVALUATION_DISPOSITIONS = (
    "USE",
    "PARTIAL_USE",
    "KEEP_AVAILABLE",
    "SUPERSEDE",
    "DISCARD",
    "REQUEST_UPDATED_B",
)

FAILURE_CLASSES = (
    "AUTHORITY_NOT_GRANTED",
    "SCOPE_MISMATCH",
    "STALE_STATE_VERSION",
    "GRANT_REVOKED",
    "GRANT_EXPIRED",
    "CAPABILITY_BOUNDARY_VIOLATION",
    "RESOURCE_SCOPE_MISMATCH",
    "SAFETY_SCOPE_MISMATCH",
    "PERMISSION_SCOPE_MISMATCH",
    "B_LOOP_CONTROL_FORBIDDEN",
    "B_RECURSIVE_DELEGATION_FORBIDDEN",
    "B_CONCERN_CREATION_FORBIDDEN",
    "INVALID_RESULT_RECEIVER",
)

B_FORBIDDEN_AUTHORITIES = (
    "SELECT_CURRENT_NEED",
    "JUDGE_LOCAL_SUFFICIENCY",
    "DECIDE_LOCAL_CONTINUATION",
    "ADOPT_RESULT",
    "CONTROL_LOOP",
    "CREATE_CONCERN",
    "SPLIT_CONCERN",
    "MERGE_CONCERN",
    "DELEGATE_B_RECURSIVELY",
    "DECLARE_WORLD_TRUTH",
)

__all__ = [
    "A_AUTHORITIES",
    "B_CR_AUTHORITIES",
    "B_FORBIDDEN_AUTHORITIES",
    "B_RESULT_STATUSES",
    "EVALUATION_DISPOSITIONS",
    "FAILURE_CLASSES",
    "LOOP_COMMAND_CAPABILITY",
    "MECHANICAL_COMMANDS",
    "PHASE",
    "REQUIRED_A_TRIGGER_AUTHORITY",
    "RESULT_EVALUATION_AUTHORITY",
    "ROLE_A",
    "ROLE_B",
]
