from __future__ import annotations

from typing import Any, Dict, Tuple

from .field_state_reducer_behavior_policy_controlled_dryrun_types_v1 import (
    BehaviorPolicyDryRunCaseV1,
)


def _case(
    case_id: str,
    category: str,
    fixture_refs: Tuple[str, ...],
    input_overrides: Dict[str, Any],
    expected_validation: bool,
    expected_error_code: str | None,
    expected_decision_outcome: str | None,
    deterministic_comparison_required: bool,
) -> BehaviorPolicyDryRunCaseV1:
    return BehaviorPolicyDryRunCaseV1(
        case_id=case_id,
        category=category,
        fixture_refs=fixture_refs,
        input_overrides=input_overrides,
        expected_validation=expected_validation,
        expected_error_code=expected_error_code,
        expected_decision_outcome=expected_decision_outcome,
        expected_selected_policy_ids=tuple(),
        expected_resulting_state_candidate=None,
        expected_policy_execution_executed=False,
        expected_state_mutation_executed=False,
        expected_runtime_execution=False,
        deterministic_comparison_required=deterministic_comparison_required,
    )


FIELD_STATE_REDUCER_BEHAVIOR_POLICY_CONTROLLED_DRYRUN_CASES_V1: Tuple[
    BehaviorPolicyDryRunCaseV1, ...
] = (
    _case(
        case_id="registry_loading_case",
        category="positive",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={"state_type": "path_state"},
        expected_validation=True,
        expected_error_code=None,
        expected_decision_outcome="skeleton_policy_decision",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="baseline_placeholder_chain_case",
        category="positive",
        fixture_refs=("latest_valid_candidate", "confidence_candidate"),
        input_overrides={"state_type": "path_state"},
        expected_validation=True,
        expected_error_code=None,
        expected_decision_outcome="skeleton_policy_decision",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="repeated_identical_input_case",
        category="positive",
        fixture_refs=("confidence_candidate", "consensus_candidate"),
        input_overrides={"state_type": "presence_state"},
        expected_validation=True,
        expected_error_code=None,
        expected_decision_outcome="skeleton_policy_decision",
        deterministic_comparison_required=True,
    ),
    _case(
        case_id="reversed_candidate_order_case",
        category="positive",
        fixture_refs=("confidence_candidate", "consensus_candidate"),
        input_overrides={
            "state_type": "presence_state",
            "candidate_policy_ids": (
                "highest_confidence_valid_event",
                "multi_event_consensus",
                "no_state_change",
            ),
            "candidate_policy_ids_reversed": (
                "no_state_change",
                "multi_event_consensus",
                "highest_confidence_valid_event",
            ),
        },
        expected_validation=True,
        expected_error_code=None,
        expected_decision_outcome="skeleton_policy_decision",
        deterministic_comparison_required=True,
    ),
    _case(
        case_id="conflict_preservation_candidate_case",
        category="positive",
        fixture_refs=("conflict_preservation_candidate",),
        input_overrides={
            "state_type": "conflict_state",
            "conflict_inputs": {"mode": "preserve"},
        },
        expected_validation=True,
        expected_error_code=None,
        expected_decision_outcome="skeleton_policy_decision",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="temporary_overlay_candidate_case",
        category="positive",
        fixture_refs=("temporary_overlay_candidate",),
        input_overrides={
            "state_type": "temporary_overlay_state",
            "overlay_inputs": {"separate": True},
        },
        expected_validation=True,
        expected_error_code=None,
        expected_decision_outcome="skeleton_policy_decision",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="owner_correction_candidate_case",
        category="positive",
        fixture_refs=("owner_correction_candidate",),
        input_overrides={
            "state_type": "facility_state",
            "owner_correction_inputs": {"candidate_only": True},
        },
        expected_validation=True,
        expected_error_code=None,
        expected_decision_outcome="skeleton_policy_decision",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="insufficient_evidence_no_state_change_case",
        category="positive",
        fixture_refs=("insufficient_evidence_candidate",),
        input_overrides={
            "state_type": "uncertainty_state",
            "confidence_inputs": {"evidence": "insufficient"},
        },
        expected_validation=True,
        expected_error_code=None,
        expected_decision_outcome="skeleton_policy_decision",
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="unknown_policy_id_rejection_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={
            "state_type": "path_state",
            "candidate_policy_ids": ("unknown_policy",),
        },
        expected_validation=False,
        expected_error_code="unknown_policy_id",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="unknown_state_type_rejection_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={"state_type": "unknown_state"},
        expected_validation=False,
        expected_error_code="unknown_state_type",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="missing_policy_registry_snapshot_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={
            "state_type": "path_state",
            "snapshot_overrides": {"policy_registry_snapshot": ""},
        },
        expected_validation=False,
        expected_error_code="missing_policy_registry_snapshot",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="missing_eligibility_snapshot_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={
            "state_type": "path_state",
            "snapshot_overrides": {"eligibility_matrix_snapshot": ""},
        },
        expected_validation=False,
        expected_error_code="missing_eligibility_matrix_snapshot",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="missing_precedence_snapshot_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={
            "state_type": "path_state",
            "snapshot_overrides": {"precedence_snapshot": ""},
        },
        expected_validation=False,
        expected_error_code="missing_precedence_snapshot",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="missing_composition_snapshot_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={
            "state_type": "path_state",
            "snapshot_overrides": {"composition_snapshot": ""},
        },
        expected_validation=False,
        expected_error_code="missing_composition_snapshot",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="runtime_request_rejection_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={"state_type": "path_state", "runtime_requested": True},
        expected_validation=False,
        expected_error_code="runtime_execution_forbidden",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="direct_state_write_rejection_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={"state_type": "path_state", "state_write_requested": True},
        expected_validation=False,
        expected_error_code="direct_state_write_forbidden",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="fact_promotion_rejection_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={"state_type": "path_state", "fact_promotion_requested": True},
        expected_validation=False,
        expected_error_code="fact_promotion_forbidden",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="action_trigger_rejection_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={"state_type": "path_state", "action_trigger_requested": True},
        expected_validation=False,
        expected_error_code="action_trigger_forbidden",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="provider_recall_rejection_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={"state_type": "path_state", "provider_recall_requested": True},
        expected_validation=False,
        expected_error_code="provider_recall_forbidden",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
    _case(
        case_id="external_lookup_rejection_case",
        category="negative",
        fixture_refs=("latest_valid_candidate",),
        input_overrides={"state_type": "path_state", "external_lookup_requested": True},
        expected_validation=False,
        expected_error_code="external_lookup_forbidden",
        expected_decision_outcome=None,
        deterministic_comparison_required=False,
    ),
)
