from __future__ import annotations

from typing import Dict, Tuple


FIELD_STATE_REDUCER_BEHAVIOR_POLICY_REGISTRY_SKELETON_V1: Tuple[
    Dict[str, object], ...
] = (
    {
        "policy_id": "latest_valid_event",
        "policy_version": "v1",
        "eligible_state_types": (
            "path_state",
            "environmental_condition_state",
            "temporary_overlay_state",
        ),
        "precedence_class": "selection_low",
        "composable_with": ("expiration_degrade", "temporary_overlay_separation"),
        "mutually_exclusive_with": ("revocation_override",),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "highest_confidence_valid_event",
        "policy_version": "v1",
        "eligible_state_types": (
            "navigation_relevance_state",
            "presence_state",
            "accessibility_state",
        ),
        "precedence_class": "selection_low",
        "composable_with": (
            "multi_event_consensus",
            "insufficient_evidence_unresolved",
        ),
        "mutually_exclusive_with": ("revocation_override",),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "multi_event_consensus",
        "policy_version": "v1",
        "eligible_state_types": (
            "presence_state",
            "facility_state",
            "service_state",
            "accessibility_state",
            "entity_field_observation_relation_state",
        ),
        "precedence_class": "selection_mid",
        "composable_with": ("highest_confidence_valid_event", "conflict_preservation"),
        "mutually_exclusive_with": tuple(),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "negative_event_override",
        "policy_version": "v1",
        "eligible_state_types": (
            "obstruction_state",
            "accessibility_state",
            "environmental_condition_state",
        ),
        "precedence_class": "selection_high",
        "composable_with": (
            "insufficient_evidence_unresolved",
            "conflict_preservation",
        ),
        "mutually_exclusive_with": tuple(),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "revocation_override",
        "policy_version": "v1",
        "eligible_state_types": (
            "presence_state",
            "accessibility_state",
            "path_state",
            "service_state",
            "facility_state",
        ),
        "precedence_class": "override_top",
        "composable_with": ("no_state_change",),
        "mutually_exclusive_with": (
            "latest_valid_event",
            "highest_confidence_valid_event",
        ),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "expiration_degrade",
        "policy_version": "v1",
        "eligible_state_types": (
            "presence_state",
            "accessibility_state",
            "service_state",
            "environmental_condition_state",
        ),
        "precedence_class": "override_high",
        "composable_with": ("insufficient_evidence_unresolved",),
        "mutually_exclusive_with": tuple(),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "temporary_overlay_separation",
        "policy_version": "v1",
        "eligible_state_types": (
            "temporary_overlay_state",
            "accessibility_state",
            "path_state",
        ),
        "precedence_class": "overlay_high",
        "composable_with": ("conflict_preservation", "expiration_degrade"),
        "mutually_exclusive_with": tuple(),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "conflict_preservation",
        "policy_version": "v1",
        "eligible_state_types": (
            "conflict_state",
            "uncertainty_state",
            "accessibility_state",
            "path_state",
        ),
        "precedence_class": "safety_top",
        "composable_with": (
            "insufficient_evidence_unresolved",
            "temporary_overlay_separation",
        ),
        "mutually_exclusive_with": tuple(),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "insufficient_evidence_unresolved",
        "policy_version": "v1",
        "eligible_state_types": (
            "uncertainty_state",
            "conflict_state",
            "human_activity_state",
            "service_state",
            "entity_field_observation_relation_state",
        ),
        "precedence_class": "safety_high",
        "composable_with": ("expiration_degrade", "conflict_preservation"),
        "mutually_exclusive_with": tuple(),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "explicit_owner_override_candidate",
        "policy_version": "v1",
        "eligible_state_types": (
            "facility_state",
            "service_state",
            "navigation_relevance_state",
        ),
        "precedence_class": "governed_mid",
        "composable_with": ("multi_event_consensus", "conflict_preservation"),
        "mutually_exclusive_with": tuple(),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
    {
        "policy_id": "no_state_change",
        "policy_version": "v1",
        "eligible_state_types": (
            "presence_state",
            "accessibility_state",
            "path_state",
            "obstruction_state",
            "facility_state",
            "service_state",
            "environmental_condition_state",
            "human_activity_state",
            "navigation_relevance_state",
            "temporary_overlay_state",
            "uncertainty_state",
            "conflict_state",
        ),
        "precedence_class": "fallback",
        "composable_with": (
            "revocation_override",
            "insufficient_evidence_unresolved",
            "conflict_preservation",
        ),
        "mutually_exclusive_with": tuple(),
        "deterministic_required": True,
        "implemented": False,
        "runtime_callable": False,
        "real_execution": False,
        "fact_promotion_allowed": False,
        "state_write_allowed": False,
        "action_trigger_allowed": False,
    },
)


def policy_ids_v1() -> Tuple[str, ...]:
    return tuple(
        str(entry["policy_id"])
        for entry in FIELD_STATE_REDUCER_BEHAVIOR_POLICY_REGISTRY_SKELETON_V1
    )
