from __future__ import annotations

from typing import Dict, Tuple


FIELD_STATE_REDUCER_BEHAVIOR_POLICY_FIXTURES_V1: Tuple[Dict[str, object], ...] = (
    {
        "fixture_id": "latest_valid_candidate",
        "policy_id": "latest_valid_event",
        "state_type": "path_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
    {
        "fixture_id": "revocation_candidate",
        "policy_id": "revocation_override",
        "state_type": "accessibility_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
    {
        "fixture_id": "confidence_candidate",
        "policy_id": "highest_confidence_valid_event",
        "state_type": "navigation_relevance_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
    {
        "fixture_id": "consensus_candidate",
        "policy_id": "multi_event_consensus",
        "state_type": "presence_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
    {
        "fixture_id": "conflict_preservation_candidate",
        "policy_id": "conflict_preservation",
        "state_type": "conflict_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
    {
        "fixture_id": "insufficient_evidence_candidate",
        "policy_id": "insufficient_evidence_unresolved",
        "state_type": "uncertainty_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
    {
        "fixture_id": "temporary_overlay_candidate",
        "policy_id": "temporary_overlay_separation",
        "state_type": "temporary_overlay_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
    {
        "fixture_id": "owner_correction_candidate",
        "policy_id": "explicit_owner_override_candidate",
        "state_type": "facility_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
    {
        "fixture_id": "no_state_change_candidate",
        "policy_id": "no_state_change",
        "state_type": "service_state",
        "synthetic": True,
        "production_data": False,
        "real_event": False,
        "policy_execution_allowed": False,
        "state_mutation_allowed": False,
    },
)
