"""
Luna Badge 常量定义 (v1.2.0)
"""

# API版本
API_VERSION = "v1.2.0"

# 模块名称
MODULE_TTS = "TTS"
MODULE_VISION = "Vision"
MODULE_NAVIGATION = "Navigation"
MODULE_SCENE = "Scene"
MODULE_PATH = "Path"
MODULE_PERFORMANCE = "Performance"
MODULE_EVENT = "Event"
MODULE_SYSTEM = "System"

# HTTP状态码
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_ERROR = 500

# 默认值
DEFAULT_TIMEOUT = 30
DEFAULT_MAX_RETRIES = 3



